// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginreward/loginrecord.proto

package protocols.loginreward;

public final class loginrecord {
  private loginrecord() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:request)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 请求
   * </pre>
   *
   * Protobuf type {@code request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:request)
      requestOrBuilder {
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.loginreward.loginrecord.internal_static_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.loginreward.loginrecord.internal_static_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.loginreward.loginrecord.request.class, protocols.loginreward.loginrecord.request.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.loginreward.loginrecord.request)) {
        return super.equals(obj);
      }
      protocols.loginreward.loginrecord.request other = (protocols.loginreward.loginrecord.request) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.loginreward.loginrecord.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.loginreward.loginrecord.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求
     * </pre>
     *
     * Protobuf type {@code request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:request)
        protocols.loginreward.loginrecord.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.loginreward.loginrecord.internal_static_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.loginreward.loginrecord.internal_static_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.loginreward.loginrecord.request.class, protocols.loginreward.loginrecord.request.Builder.class);
      }

      // Construct using protocols.loginreward.loginrecord.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.loginreward.loginrecord.internal_static_request_descriptor;
      }

      public protocols.loginreward.loginrecord.request getDefaultInstanceForType() {
        return protocols.loginreward.loginrecord.request.getDefaultInstance();
      }

      public protocols.loginreward.loginrecord.request build() {
        protocols.loginreward.loginrecord.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.loginreward.loginrecord.request buildPartial() {
        protocols.loginreward.loginrecord.request result = new protocols.loginreward.loginrecord.request(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.loginreward.loginrecord.request) {
          return mergeFrom((protocols.loginreward.loginrecord.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.loginreward.loginrecord.request other) {
        if (other == protocols.loginreward.loginrecord.request.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.loginreward.loginrecord.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.loginreward.loginrecord.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:request)
    }

    // @@protoc_insertion_point(class_scope:request)
    private static final protocols.loginreward.loginrecord.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.loginreward.loginrecord.request();
    }

    public static protocols.loginreward.loginrecord.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    public protocols.loginreward.loginrecord.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    java.util.List<protocols.loginreward.loginrecord.record_t> 
        getRecordsList();
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    protocols.loginreward.loginrecord.record_t getRecords(int index);
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    int getRecordsCount();
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    java.util.List<? extends protocols.loginreward.loginrecord.record_tOrBuilder> 
        getRecordsOrBuilderList();
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    protocols.loginreward.loginrecord.record_tOrBuilder getRecordsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * Protobuf type {@code response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:response)
      responseOrBuilder {
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      records_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                records_ = new java.util.ArrayList<protocols.loginreward.loginrecord.record_t>();
                mutable_bitField0_ |= 0x00000001;
              }
              records_.add(
                  input.readMessage(protocols.loginreward.loginrecord.record_t.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          records_ = java.util.Collections.unmodifiableList(records_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.loginreward.loginrecord.internal_static_response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.loginreward.loginrecord.internal_static_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.loginreward.loginrecord.response.class, protocols.loginreward.loginrecord.response.Builder.class);
    }

    public static final int RECORDS_FIELD_NUMBER = 1;
    private java.util.List<protocols.loginreward.loginrecord.record_t> records_;
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    public java.util.List<protocols.loginreward.loginrecord.record_t> getRecordsList() {
      return records_;
    }
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    public java.util.List<? extends protocols.loginreward.loginrecord.record_tOrBuilder> 
        getRecordsOrBuilderList() {
      return records_;
    }
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    public int getRecordsCount() {
      return records_.size();
    }
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    public protocols.loginreward.loginrecord.record_t getRecords(int index) {
      return records_.get(index);
    }
    /**
     * <pre>
     * 登录记录
     * </pre>
     *
     * <code>repeated .record_t records = 1;</code>
     */
    public protocols.loginreward.loginrecord.record_tOrBuilder getRecordsOrBuilder(
        int index) {
      return records_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < records_.size(); i++) {
        output.writeMessage(1, records_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < records_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, records_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.loginreward.loginrecord.response)) {
        return super.equals(obj);
      }
      protocols.loginreward.loginrecord.response other = (protocols.loginreward.loginrecord.response) obj;

      boolean result = true;
      result = result && getRecordsList()
          .equals(other.getRecordsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecordsCount() > 0) {
        hash = (37 * hash) + RECORDS_FIELD_NUMBER;
        hash = (53 * hash) + getRecordsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.loginreward.loginrecord.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.loginreward.loginrecord.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回
     * </pre>
     *
     * Protobuf type {@code response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response)
        protocols.loginreward.loginrecord.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.loginreward.loginrecord.internal_static_response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.loginreward.loginrecord.internal_static_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.loginreward.loginrecord.response.class, protocols.loginreward.loginrecord.response.Builder.class);
      }

      // Construct using protocols.loginreward.loginrecord.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.loginreward.loginrecord.internal_static_response_descriptor;
      }

      public protocols.loginreward.loginrecord.response getDefaultInstanceForType() {
        return protocols.loginreward.loginrecord.response.getDefaultInstance();
      }

      public protocols.loginreward.loginrecord.response build() {
        protocols.loginreward.loginrecord.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.loginreward.loginrecord.response buildPartial() {
        protocols.loginreward.loginrecord.response result = new protocols.loginreward.loginrecord.response(this);
        int from_bitField0_ = bitField0_;
        if (recordsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            records_ = java.util.Collections.unmodifiableList(records_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.records_ = records_;
        } else {
          result.records_ = recordsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.loginreward.loginrecord.response) {
          return mergeFrom((protocols.loginreward.loginrecord.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.loginreward.loginrecord.response other) {
        if (other == protocols.loginreward.loginrecord.response.getDefaultInstance()) return this;
        if (recordsBuilder_ == null) {
          if (!other.records_.isEmpty()) {
            if (records_.isEmpty()) {
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordsIsMutable();
              records_.addAll(other.records_);
            }
            onChanged();
          }
        } else {
          if (!other.records_.isEmpty()) {
            if (recordsBuilder_.isEmpty()) {
              recordsBuilder_.dispose();
              recordsBuilder_ = null;
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordsFieldBuilder() : null;
            } else {
              recordsBuilder_.addAllMessages(other.records_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.loginreward.loginrecord.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.loginreward.loginrecord.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protocols.loginreward.loginrecord.record_t> records_ =
        java.util.Collections.emptyList();
      private void ensureRecordsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          records_ = new java.util.ArrayList<protocols.loginreward.loginrecord.record_t>(records_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.loginreward.loginrecord.record_t, protocols.loginreward.loginrecord.record_t.Builder, protocols.loginreward.loginrecord.record_tOrBuilder> recordsBuilder_;

      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public java.util.List<protocols.loginreward.loginrecord.record_t> getRecordsList() {
        if (recordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(records_);
        } else {
          return recordsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public int getRecordsCount() {
        if (recordsBuilder_ == null) {
          return records_.size();
        } else {
          return recordsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public protocols.loginreward.loginrecord.record_t getRecords(int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);
        } else {
          return recordsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder setRecords(
          int index, protocols.loginreward.loginrecord.record_t value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.set(index, value);
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder setRecords(
          int index, protocols.loginreward.loginrecord.record_t.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder addRecords(protocols.loginreward.loginrecord.record_t value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder addRecords(
          int index, protocols.loginreward.loginrecord.record_t value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(index, value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder addRecords(
          protocols.loginreward.loginrecord.record_t.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder addRecords(
          int index, protocols.loginreward.loginrecord.record_t.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder addAllRecords(
          java.lang.Iterable<? extends protocols.loginreward.loginrecord.record_t> values) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, records_);
          onChanged();
        } else {
          recordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder clearRecords() {
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public Builder removeRecords(int index) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.remove(index);
          onChanged();
        } else {
          recordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public protocols.loginreward.loginrecord.record_t.Builder getRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public protocols.loginreward.loginrecord.record_tOrBuilder getRecordsOrBuilder(
          int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);  } else {
          return recordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public java.util.List<? extends protocols.loginreward.loginrecord.record_tOrBuilder> 
           getRecordsOrBuilderList() {
        if (recordsBuilder_ != null) {
          return recordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(records_);
        }
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public protocols.loginreward.loginrecord.record_t.Builder addRecordsBuilder() {
        return getRecordsFieldBuilder().addBuilder(
            protocols.loginreward.loginrecord.record_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public protocols.loginreward.loginrecord.record_t.Builder addRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().addBuilder(
            index, protocols.loginreward.loginrecord.record_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 登录记录
       * </pre>
       *
       * <code>repeated .record_t records = 1;</code>
       */
      public java.util.List<protocols.loginreward.loginrecord.record_t.Builder> 
           getRecordsBuilderList() {
        return getRecordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.loginreward.loginrecord.record_t, protocols.loginreward.loginrecord.record_t.Builder, protocols.loginreward.loginrecord.record_tOrBuilder> 
          getRecordsFieldBuilder() {
        if (recordsBuilder_ == null) {
          recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocols.loginreward.loginrecord.record_t, protocols.loginreward.loginrecord.record_t.Builder, protocols.loginreward.loginrecord.record_tOrBuilder>(
                  records_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          records_ = null;
        }
        return recordsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:response)
    }

    // @@protoc_insertion_point(class_scope:response)
    private static final protocols.loginreward.loginrecord.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.loginreward.loginrecord.response();
    }

    public static protocols.loginreward.loginrecord.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    public protocols.loginreward.loginrecord.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface record_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:record_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 第几天
     * </pre>
     *
     * <code>uint32 day = 1;</code>
     */
    int getDay();

    /**
     * <pre>
     * 是否已登录
     * </pre>
     *
     * <code>bool isLogin = 2;</code>
     */
    boolean getIsLogin();

    /**
     * <pre>
     * 是否领奖了
     * </pre>
     *
     * <code>bool isGotPrize = 3;</code>
     */
    boolean getIsGotPrize();

    /**
     * <pre>
     * 房卡数
     * </pre>
     *
     * <code>uint32 roomcard = 4;</code>
     */
    int getRoomcard();
  }
  /**
   * <pre>
   * 一天的记录
   * </pre>
   *
   * Protobuf type {@code record_t}
   */
  public  static final class record_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:record_t)
      record_tOrBuilder {
    // Use record_t.newBuilder() to construct.
    private record_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private record_t() {
      day_ = 0;
      isLogin_ = false;
      isGotPrize_ = false;
      roomcard_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private record_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              day_ = input.readUInt32();
              break;
            }
            case 16: {

              isLogin_ = input.readBool();
              break;
            }
            case 24: {

              isGotPrize_ = input.readBool();
              break;
            }
            case 32: {

              roomcard_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.loginreward.loginrecord.internal_static_record_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.loginreward.loginrecord.internal_static_record_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.loginreward.loginrecord.record_t.class, protocols.loginreward.loginrecord.record_t.Builder.class);
    }

    public static final int DAY_FIELD_NUMBER = 1;
    private int day_;
    /**
     * <pre>
     * 第几天
     * </pre>
     *
     * <code>uint32 day = 1;</code>
     */
    public int getDay() {
      return day_;
    }

    public static final int ISLOGIN_FIELD_NUMBER = 2;
    private boolean isLogin_;
    /**
     * <pre>
     * 是否已登录
     * </pre>
     *
     * <code>bool isLogin = 2;</code>
     */
    public boolean getIsLogin() {
      return isLogin_;
    }

    public static final int ISGOTPRIZE_FIELD_NUMBER = 3;
    private boolean isGotPrize_;
    /**
     * <pre>
     * 是否领奖了
     * </pre>
     *
     * <code>bool isGotPrize = 3;</code>
     */
    public boolean getIsGotPrize() {
      return isGotPrize_;
    }

    public static final int ROOMCARD_FIELD_NUMBER = 4;
    private int roomcard_;
    /**
     * <pre>
     * 房卡数
     * </pre>
     *
     * <code>uint32 roomcard = 4;</code>
     */
    public int getRoomcard() {
      return roomcard_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (day_ != 0) {
        output.writeUInt32(1, day_);
      }
      if (isLogin_ != false) {
        output.writeBool(2, isLogin_);
      }
      if (isGotPrize_ != false) {
        output.writeBool(3, isGotPrize_);
      }
      if (roomcard_ != 0) {
        output.writeUInt32(4, roomcard_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, day_);
      }
      if (isLogin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isLogin_);
      }
      if (isGotPrize_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isGotPrize_);
      }
      if (roomcard_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, roomcard_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.loginreward.loginrecord.record_t)) {
        return super.equals(obj);
      }
      protocols.loginreward.loginrecord.record_t other = (protocols.loginreward.loginrecord.record_t) obj;

      boolean result = true;
      result = result && (getDay()
          == other.getDay());
      result = result && (getIsLogin()
          == other.getIsLogin());
      result = result && (getIsGotPrize()
          == other.getIsGotPrize());
      result = result && (getRoomcard()
          == other.getRoomcard());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + ISLOGIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLogin());
      hash = (37 * hash) + ISGOTPRIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsGotPrize());
      hash = (37 * hash) + ROOMCARD_FIELD_NUMBER;
      hash = (53 * hash) + getRoomcard();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.loginreward.loginrecord.record_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.record_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.record_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.loginreward.loginrecord.record_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.loginreward.loginrecord.record_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 一天的记录
     * </pre>
     *
     * Protobuf type {@code record_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:record_t)
        protocols.loginreward.loginrecord.record_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.loginreward.loginrecord.internal_static_record_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.loginreward.loginrecord.internal_static_record_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.loginreward.loginrecord.record_t.class, protocols.loginreward.loginrecord.record_t.Builder.class);
      }

      // Construct using protocols.loginreward.loginrecord.record_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        day_ = 0;

        isLogin_ = false;

        isGotPrize_ = false;

        roomcard_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.loginreward.loginrecord.internal_static_record_t_descriptor;
      }

      public protocols.loginreward.loginrecord.record_t getDefaultInstanceForType() {
        return protocols.loginreward.loginrecord.record_t.getDefaultInstance();
      }

      public protocols.loginreward.loginrecord.record_t build() {
        protocols.loginreward.loginrecord.record_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.loginreward.loginrecord.record_t buildPartial() {
        protocols.loginreward.loginrecord.record_t result = new protocols.loginreward.loginrecord.record_t(this);
        result.day_ = day_;
        result.isLogin_ = isLogin_;
        result.isGotPrize_ = isGotPrize_;
        result.roomcard_ = roomcard_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.loginreward.loginrecord.record_t) {
          return mergeFrom((protocols.loginreward.loginrecord.record_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.loginreward.loginrecord.record_t other) {
        if (other == protocols.loginreward.loginrecord.record_t.getDefaultInstance()) return this;
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getIsLogin() != false) {
          setIsLogin(other.getIsLogin());
        }
        if (other.getIsGotPrize() != false) {
          setIsGotPrize(other.getIsGotPrize());
        }
        if (other.getRoomcard() != 0) {
          setRoomcard(other.getRoomcard());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.loginreward.loginrecord.record_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.loginreward.loginrecord.record_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int day_ ;
      /**
       * <pre>
       * 第几天
       * </pre>
       *
       * <code>uint32 day = 1;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <pre>
       * 第几天
       * </pre>
       *
       * <code>uint32 day = 1;</code>
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 第几天
       * </pre>
       *
       * <code>uint32 day = 1;</code>
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private boolean isLogin_ ;
      /**
       * <pre>
       * 是否已登录
       * </pre>
       *
       * <code>bool isLogin = 2;</code>
       */
      public boolean getIsLogin() {
        return isLogin_;
      }
      /**
       * <pre>
       * 是否已登录
       * </pre>
       *
       * <code>bool isLogin = 2;</code>
       */
      public Builder setIsLogin(boolean value) {
        
        isLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否已登录
       * </pre>
       *
       * <code>bool isLogin = 2;</code>
       */
      public Builder clearIsLogin() {
        
        isLogin_ = false;
        onChanged();
        return this;
      }

      private boolean isGotPrize_ ;
      /**
       * <pre>
       * 是否领奖了
       * </pre>
       *
       * <code>bool isGotPrize = 3;</code>
       */
      public boolean getIsGotPrize() {
        return isGotPrize_;
      }
      /**
       * <pre>
       * 是否领奖了
       * </pre>
       *
       * <code>bool isGotPrize = 3;</code>
       */
      public Builder setIsGotPrize(boolean value) {
        
        isGotPrize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否领奖了
       * </pre>
       *
       * <code>bool isGotPrize = 3;</code>
       */
      public Builder clearIsGotPrize() {
        
        isGotPrize_ = false;
        onChanged();
        return this;
      }

      private int roomcard_ ;
      /**
       * <pre>
       * 房卡数
       * </pre>
       *
       * <code>uint32 roomcard = 4;</code>
       */
      public int getRoomcard() {
        return roomcard_;
      }
      /**
       * <pre>
       * 房卡数
       * </pre>
       *
       * <code>uint32 roomcard = 4;</code>
       */
      public Builder setRoomcard(int value) {
        
        roomcard_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 房卡数
       * </pre>
       *
       * <code>uint32 roomcard = 4;</code>
       */
      public Builder clearRoomcard() {
        
        roomcard_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:record_t)
    }

    // @@protoc_insertion_point(class_scope:record_t)
    private static final protocols.loginreward.loginrecord.record_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.loginreward.loginrecord.record_t();
    }

    public static protocols.loginreward.loginrecord.record_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<record_t>
        PARSER = new com.google.protobuf.AbstractParser<record_t>() {
      public record_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new record_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<record_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<record_t> getParserForType() {
      return PARSER;
    }

    public protocols.loginreward.loginrecord.record_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_record_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_record_t_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035loginreward/loginrecord.proto\"\t\n\007reque" +
      "st\"&\n\010response\022\032\n\007records\030\001 \003(\0132\t.record" +
      "_t\"N\n\010record_t\022\013\n\003day\030\001 \001(\r\022\017\n\007isLogin\030\002" +
      " \001(\010\022\022\n\nisGotPrize\030\003 \001(\010\022\020\n\010roomcard\030\004 \001" +
      "(\rB$\n\025protocols.loginrewardB\013loginrecord" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { });
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Records", });
    internal_static_record_t_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_record_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_record_t_descriptor,
        new java.lang.String[] { "Day", "IsLogin", "IsGotPrize", "Roomcard", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
