/*
* @Brief: Java Persistence Class (JPC) for Database Table.
*
* @Class: Agent
* @Namespace: com.mozat.morange.dbcache.tables
* @Table: AGENT
* @Primary Key: ID
* @Identity: ID
* @Unique Index: [u'ID']
*
* @Caution: This file is Auto Generated.
*     DO NOT modify this file EVEN IF you know what you are doing.
*/

package com.mozat.morange.dbcache.tables;

import java.util.ArrayList;
import java.util.HashMap;
import com.mozat.morange.dbcache.core.TableBase;
import com.mozat.morange.dbcache.core.TableCache;
import com.mozat.morange.dbcache.core.QueryCriteria;

public final class Agent extends TableBase implements java.io.Serializable{
    // Serializable ID
    private static final long serialVersionUID = 1L;

    private static TableCache _tableCache;
    private static String _tableName;

    private static boolean _isIdAutoGenerated = true;

    /**
    * This method is used by the engine.<br>
    * DON'T use this method under any circumstances.
    */
    @Override
    public TableCache _getTableCache(){return _tableCache;}

    /**
    * Never manually run SQL statements using TableCache Object.<br>
    * Think twice before hand-writing ANY SQL statements, and use it carefully.
    */
    @Deprecated
    public static TableCache __getTableCache(){return _tableCache;}

    @Override
    public String _getTableName(){return _tableName;}

    public static String __getTableName(){return _tableName;}

    public static void setCacheAndName(TableCache cache, String name){
        _tableCache = cache;
        _tableName = name;
    }

    @Override
    public Long _getIdValue(){
        Integer _idVal = this.ID;
        return _idVal.longValue();
    }

    @Override
    public void _setIdValue(Long _val){
        this.ID = _val.intValue();
    }

    @Override
    public boolean _isIdAutoGenerated(){
        return _isIdAutoGenerated;
    }


    // SQL templates
    private static final String _updateSQL = "UPDATE AGENT SET `LOGIN_ID` = ?, `PARENT_AGENT_ID` = ?, `NAME` = ?, `PWD` = ?, `PHONE` = ?, `ROOM_CARD_COUNT` = ?, `COIN_COUNT` = ?, `LEVEL` = ?, `DISCOUNT` = ?, `IS_ADMIN` = ?, `CREATE_TIME` = ?, `DELETED` = ?, `DELETE_TIME` = ? WHERE `ID` = ?;";
    private static final String _querySQL = "SELECT * FROM AGENT WHERE `ID` = ?;";
    private static final String _createSQL = "INSERT INTO AGENT (`LOGIN_ID`, `PARENT_AGENT_ID`, `NAME`, `PWD`, `PHONE`, `ROOM_CARD_COUNT`, `COIN_COUNT`, `LEVEL`, `DISCOUNT`, `IS_ADMIN`, `CREATE_TIME`, `DELETED`, `DELETE_TIME`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
    private static final String _deleteSQL = "DELETE FROM AGENT WHERE `ID` = ?;";

    // Field Map
    private static HashMap<String, Integer> AttrFieldMap;
    private static HashMap<String, Integer> getFieldMap(){
        if (AttrFieldMap == null){
            AttrFieldMap = new HashMap<String, Integer>();
            AttrFieldMap.put("ID", 1);
            AttrFieldMap.put("LOGIN_ID", 2);
            AttrFieldMap.put("PARENT_AGENT_ID", 3);
            AttrFieldMap.put("NAME", 4);
            AttrFieldMap.put("PWD", 5);
            AttrFieldMap.put("PHONE", 6);
            AttrFieldMap.put("ROOM_CARD_COUNT", 7);
            AttrFieldMap.put("COIN_COUNT", 8);
            AttrFieldMap.put("LEVEL", 9);
            AttrFieldMap.put("DISCOUNT", 10);
            AttrFieldMap.put("IS_ADMIN", 11);
            AttrFieldMap.put("CREATE_TIME", 12);
            AttrFieldMap.put("DELETED", 13);
            AttrFieldMap.put("DELETE_TIME", 14);
        }

        return AttrFieldMap;
    }

    // Attributes Wrapper for Query
    public static final TableBase.Attribute<Integer> AttrID = new TableBase.Attribute<Integer>("ID", Agent.class, 1);
    public static final TableBase.AttributeS AttrLOGIN_ID = new TableBase.AttributeS("LOGIN_ID", Agent.class, 2);
    public static final TableBase.AttributeS AttrPARENT_AGENT_ID = new TableBase.AttributeS("PARENT_AGENT_ID", Agent.class, 3);
    public static final TableBase.AttributeS AttrNAME = new TableBase.AttributeS("NAME", Agent.class, 4);
    public static final TableBase.AttributeS AttrPWD = new TableBase.AttributeS("PWD", Agent.class, 5);
    public static final TableBase.AttributeS AttrPHONE = new TableBase.AttributeS("PHONE", Agent.class, 6);
    public static final TableBase.Attribute<Integer> AttrROOM_CARD_COUNT = new TableBase.Attribute<Integer>("ROOM_CARD_COUNT", Agent.class, 7);
    public static final TableBase.Attribute<Integer> AttrCOIN_COUNT = new TableBase.Attribute<Integer>("COIN_COUNT", Agent.class, 8);
    public static final TableBase.Attribute<Integer> AttrLEVEL = new TableBase.Attribute<Integer>("LEVEL", Agent.class, 9);
    public static final TableBase.AttributeS AttrDISCOUNT = new TableBase.AttributeS("DISCOUNT", Agent.class, 10);
    public static final TableBase.Attribute<Boolean> AttrIS_ADMIN = new TableBase.Attribute<Boolean>("IS_ADMIN", Agent.class, 11);
    public static final TableBase.Attribute<java.util.Date> AttrCREATE_TIME = new TableBase.Attribute<java.util.Date>("CREATE_TIME", Agent.class, 12);
    public static final TableBase.Attribute<Boolean> AttrDELETED = new TableBase.Attribute<Boolean>("DELETED", Agent.class, 13);
    public static final TableBase.Attribute<java.util.Date> AttrDELETE_TIME = new TableBase.Attribute<java.util.Date>("DELETE_TIME", Agent.class, 14);

    public static TableBase.AttributeValue<?>[] valueList(TableBase.AttributeValue<?>...valList){
        return valList;
    }

    // Member Fields.
    public int ID = 0;
    public String LOGIN_ID = "";
    public String PARENT_AGENT_ID = "";
    public String NAME = "";
    public String PWD = "";
    public String PHONE = "";
    public int ROOM_CARD_COUNT = 0;
    public int COIN_COUNT = 0;
    public int LEVEL = 0;
    public String DISCOUNT = "";
    public boolean IS_ADMIN = false;
    public java.util.Date CREATE_TIME = new java.util.Date(0);
    public boolean DELETED = false;
    public java.util.Date DELETE_TIME = new java.util.Date(0);

    // DON'T Invoke This Method Manually.
    @Override
    public HashMap<String, Integer> _getFieldMap(){
        return Agent.getFieldMap();
    }

    // DON'T Invoke This Method Manually.
    @Override
    public void _setValue(int __fidx, Object __val){
        switch (__fidx){
        case 1: {this.ID = (Integer)__val; break;}
        case 2: {this.LOGIN_ID = (String)__val; break;}
        case 3: {this.PARENT_AGENT_ID = (String)__val; break;}
        case 4: {this.NAME = (String)__val; break;}
        case 5: {this.PWD = (String)__val; break;}
        case 6: {this.PHONE = (String)__val; break;}
        case 7: {this.ROOM_CARD_COUNT = (Integer)__val; break;}
        case 8: {this.COIN_COUNT = (Integer)__val; break;}
        case 9: {this.LEVEL = (Integer)__val; break;}
        case 10: {this.DISCOUNT = (String)__val; break;}
        case 11: {this.IS_ADMIN = (Boolean)__val; break;}
        case 12: {this.CREATE_TIME = (java.util.Date)__val; break;}
        case 13: {this.DELETED = (Boolean)__val; break;}
        case 14: {this.DELETE_TIME = (java.util.Date)__val; break;}
        }
    }

    // DON'T Invoke This Method Manually.
    @Override
    @SuppressWarnings("rawtypes")
    public Comparable _getValue(int __fidx){
        switch (__fidx){
        case 1: {return this.ID;}
        case 2: {return this.LOGIN_ID;}
        case 3: {return this.PARENT_AGENT_ID;}
        case 4: {return this.NAME;}
        case 5: {return this.PWD;}
        case 6: {return this.PHONE;}
        case 7: {return this.ROOM_CARD_COUNT;}
        case 8: {return this.COIN_COUNT;}
        case 9: {return this.LEVEL;}
        case 10: {return this.DISCOUNT;}
        case 11: {return this.IS_ADMIN;}
        case 12: {return this.CREATE_TIME;}
        case 13: {return this.DELETED;}
        case 14: {return this.DELETE_TIME;}
        }
        return null;
    }

    /**
    * Default constructor for JavaBean convention
    * DON'T manually use constructor. Please use <code>create<code> instead.
    */
    public Agent(){}

    /**
    * Constructor for creating a new instance.
    * Arguments are index keys
    * DON'T manually use constructor. Please use <code>create<code> instead.
    */
    public Agent(int ID){
        this.ID = ID;
    }

    @Override
    public String _getCacheKey(){
        return _genKey(ID);
    }

    public static ArrayList<Agent> getAllObjects(){
        ArrayList<Object> __tmp = _tableCache.loadAll();

        ArrayList<Agent> __res = new ArrayList<Agent>();
        for (Object __obj: __tmp){
            __res.add((Agent)__obj);
        }

        return __res;
    }

    /**
    * update an JPO to database.
    * @return return true if updated successfully, otherwise return false
    */
    @Override
    public boolean update(){
        int __res = _tableCache.update(this, _updateSQL, 
            LOGIN_ID, PARENT_AGENT_ID, NAME, PWD, 
            PHONE, ROOM_CARD_COUNT, COIN_COUNT, LEVEL, 
            DISCOUNT, IS_ADMIN, CREATE_TIME, DELETED, 
            DELETE_TIME, ID);

        return (__res > 0);
    }

    /**
    * update JPO in batch.
    * @return num of records successfully updated.
    */
    public static int updateBatch(Agent[] objList){
        Object[][] argv = new Object[objList.length][];

        for (int idx = 0; idx < objList.length; idx++){
            Agent o = objList[idx];
            Object[] args = new Object[]{
                o.LOGIN_ID, o.PARENT_AGENT_ID, o.NAME, o.PWD, 
                o.PHONE, o.ROOM_CARD_COUNT, o.COIN_COUNT, o.LEVEL, 
                o.DISCOUNT, o.IS_ADMIN, o.CREATE_TIME, o.DELETED, 
                o.DELETE_TIME, o.ID};

            argv[idx] = args;
        }

        return _tableCache.updateBatch(objList, _updateSQL, argv);
    }

    /**
    * update JPO by QueryCriteria.
    * @return num of records successfully updated.
    */
    public static int updateByCriteria(TableBase.AttributeValue<?>[] valueList, QueryCriteria ...qcList){
        return _tableCache.updateByCriteria(valueList, qcList);
    }

    /**
    * remove an JPO from database and cache.
    * @return true if successfully removed, otherwise return false
    */
    @Override
    public boolean remove(){
        int __res = _tableCache.remove(this, _deleteSQL, ID);
        return (__res > 0);
    }

    /**
    * remove JPOs in batch from database and cache.
    * @return num of records successfully removed.
    */
    public static int removeBatch(Agent[] objList){
        Object argv[] = new Object[objList.length];

        for (int idx = 0; idx < objList.length; idx++){
            argv[idx] = objList[idx].ID;
        }

        int res = _tableCache.removeBatch(objList, _deleteSQL, argv);
        return res;
    }

    /**
    * remove JPOs from database and cache by criteria.
    * @return num of records removed.
    */
    public static int removeByCriteria(QueryCriteria qc, QueryCriteria ...moreQcs){
        return _tableCache.removeByCriteria(qc, moreQcs);
    }

    /**
    * remove all JPOs from database and cache.
    * CAUTION: this operation is irrevocable.
    * @return num of records removed.
    */
    public static int __removeAll(){
        return _tableCache.removeAll();
    }

    /**
    * create a new JPO.<br>
    * If the a record with the same index in the cache is found,<br>
    * the cached object is return, and no DB record is created.<br>
    * Otherwise a new record is created and return, and a DB record is created.
    * @return an JPO if successfully created, null otherwise.
    */
    public static Agent create(){

        Agent __newObj = new Agent();

        return (Agent) _tableCache.create(__newObj, _createSQL, 
            __newObj.LOGIN_ID, __newObj.PARENT_AGENT_ID, __newObj.NAME, __newObj.PWD, 
            __newObj.PHONE, __newObj.ROOM_CARD_COUNT, __newObj.COIN_COUNT, __newObj.LEVEL, 
            __newObj.DISCOUNT, __newObj.IS_ADMIN, __newObj.CREATE_TIME, __newObj.DELETED, 
            __newObj.DELETE_TIME);
    }

    /**
    * Create a new JPO with initial values.<br>
    * Non-auto-incremental index is required<br>
    * If a field is set for more than one time<br>,
    * subsequent set will surpass preceding set.<br>
    * If the a record with the same index in the cache is found,<br>
    * the cached object is return, and no DB record is created.<br>
    * Otherwise a new record is created and return, and a DB record is created.
    * @return an JPO if successfully created, null otherwise.
    */
    public static Agent create(
            TableBase.AttributeValue<?> attrVal,
            TableBase.AttributeValue<?>... attrVals){

        Agent __newObj = new Agent();

        if (null != attrVal.getVal()){
            __newObj._setValue(attrVal.getFidx(), attrVal.getVal());
        }

        for (TableBase.AttributeValue<?> attrV: attrVals){
            if (null != attrV.getVal()){
                __newObj._setValue(attrV.getFidx(), attrV.getVal());
            }
        }

        return (Agent) _tableCache.create(__newObj, _createSQL, 
            __newObj.LOGIN_ID, __newObj.PARENT_AGENT_ID, __newObj.NAME, __newObj.PWD, 
            __newObj.PHONE, __newObj.ROOM_CARD_COUNT, __newObj.COIN_COUNT, __newObj.LEVEL, 
            __newObj.DISCOUNT, __newObj.IS_ADMIN, __newObj.CREATE_TIME, __newObj.DELETED, 
            __newObj.DELETE_TIME);
    }

    /**
    * find a JPO by indexes.
    * @return the found JPO or null
    */
    public static Agent getOne(int ID){
        return (Agent) _tableCache.getOne(_genKey(ID), _querySQL, ID);
    }

    /**
    * find a JPO by arbitrary query criteria.
    * @return the found JPO or null
    */
    public static Agent getOneByCriteria(QueryCriteria ...criteria){
        return (Agent)_tableCache.getOneByCriteria(criteria);
    }

    /**
    * find all JPOs those match the query criteria list.
    * @return a list of JPO found.
    */
    public static ArrayList<Agent> getManyByCriteria(QueryCriteria ...criteria){
        ArrayList<Object> __tmp = _tableCache.getManyByCriteria(criteria);

        ArrayList<Agent> __res = new ArrayList<Agent>();
        for (Object __obj: __tmp){
            __res.add((Agent)__obj);
        }

        return __res;
    }

    /**
    * find a JPO by arbitrary SQL statement.
    * @return return the found JPO or null.
    */
    public static Agent getOneBySQL(String sql, Object ...args){
        return (Agent)_tableCache.getOneBySQL(sql, args);
    }

    /**
    * find all JPOs by arbitrary SQL statement.
    * @return a list of JPO found.
    */
    public static ArrayList<Agent> getManyBySQL(String sql, Object ...args){
        ArrayList<Object> __tmp = _tableCache.getManyBySQL(sql, args);

        ArrayList<Agent> __res = new ArrayList<Agent>();
        for (Object __obj: __tmp){
            __res.add((Agent)__obj);
        }

        return __res;
    }

    /**
    * query objects from database by specified class Type
    * @return a list of OBJECT found.
    */
    public static <T> ArrayList<T> getManyByArbitarySQL(Class<T> clazz, String sql, Object[] args){
        return _tableCache._queryByArbitarySQL(clazz, sql, args);
    }

}
