/*
* @Brief: Java Persistence Class (JPC) for Database Table.
*
* @Class: BTNoticationServer
* @Namespace: com.mozat.morange.dbcache.tables
* @Table: NoticationServer
* @Primary Key: monetId
* @Unique Index: ['monetId']
*
* @Caution: This file is Auto Generated.
*     DO NOT modify this file EVEN IF you know what you are doing.
*/

package com.mozat.morange.dbcache.tables;

import java.util.ArrayList;
import java.util.HashMap;
import com.mozat.morange.dbcache.core.TableBase;
import com.mozat.morange.dbcache.core.TableCache;
import com.mozat.morange.dbcache.core.QueryCriteria;

public final class BTNoticationServer extends TableBase implements java.io.Serializable{
    // Serializable ID
    private static final long serialVersionUID = 1L;

    private static TableCache _tableCache;
    private static String _tableName;

    private static boolean _isIdAutoGenerated = false;

    /**
    * This method is used by the engine.<br>
    * DON'T use this method under any circumstances.
    */
    @Override
    public TableCache _getTableCache(){return _tableCache;}

    /**
    * Never manually run SQL statements using TableCache Object.<br>
    * Think twice before hand-writing ANY SQL statements, and use it carefully.
    */
    @Deprecated
    public static TableCache __getTableCache(){return _tableCache;}

    @Override
    public String _getTableName(){return _tableName;}

    public static String __getTableName(){return _tableName;}

    public static void setCacheAndName(TableCache cache, String name){
        _tableCache = cache;
        _tableName = name;
    }

    @Override
    public Long _getIdValue(){
        Integer _idVal = this.monetId;
        return _idVal.longValue();
    }

    @Override
    public void _setIdValue(Long _val){
        this.monetId = _val.intValue();
    }

    @Override
    public boolean _isIdAutoGenerated(){
        return _isIdAutoGenerated;
    }


    // SQL templates
    private static final String _updateSQL = "UPDATE NoticationServer SET [serverId] = ? WHERE [monetId] = ?;";
    private static final String _querySQL = "SELECT * FROM NoticationServer WHERE [monetId] = ?;";
    private static final String _createSQL = "INSERT INTO NoticationServer ([monetId], [serverId]) VALUES (?, ?);";
    private static final String _deleteSQL = "DELETE FROM NoticationServer WHERE [monetId] = ?;";

    // Field Map
    private static HashMap<String, Integer> AttrFieldMap;
    private static HashMap<String, Integer> getFieldMap(){
        if (AttrFieldMap == null){
            HashMap<String,Integer> attrFieldMap = new HashMap<String, Integer>();
            attrFieldMap.put("monetId", 1);
            attrFieldMap.put("serverId", 2);
            AttrFieldMap = attrFieldMap;
        }

        return AttrFieldMap;
    }

    // Attributes Wrapper for Query
    public static final TableBase.Attribute<Integer> AttrMonetId = new TableBase.Attribute<Integer>("monetId", BTNoticationServer.class, 1);
    public static final TableBase.Attribute<Integer> AttrServerId = new TableBase.Attribute<Integer>("serverId", BTNoticationServer.class, 2);

    public static TableBase.AttributeValue<?>[] valueList(TableBase.AttributeValue<?>...valList){
        return valList;
    }

    // Member Fields.
    public int monetId = 0;
    public int serverId = 0;

    // DON'T Invoke This Method Manually.
    @Override
    public HashMap<String, Integer> _getFieldMap(){
        return BTNoticationServer.getFieldMap();
    }

    // DON'T Invoke This Method Manually.
    @Override
    public void _setValue(int __fidx, Object __val){
        switch (__fidx){
        case 1: {this.monetId = (Integer)__val; break;}
        case 2: {this.serverId = (Integer)__val; break;}
        }
    }

    // DON'T Invoke This Method Manually.
    @Override
    public Comparable _getValue(int __fidx){
        switch (__fidx){
        case 1: {return this.monetId;}
        case 2: {return this.serverId;}
        }
        return null;
    }

    /**
    * Default constructor for JavaBean convention
    * DON'T manually use constructor. Please use <code>create<code> instead.
    */
    public BTNoticationServer(){}

    /**
    * Constructor for creating a new instance.
    * Arguments are index keys
    * DON'T manually use constructor. Please use <code>create<code> instead.
    */
    public BTNoticationServer(int monetId){
        this.monetId = monetId;
    }

    @Override
    public String _getCacheKey(){
        return _genKey(monetId);
    }

    public static ArrayList<BTNoticationServer> getAllObjects(){
        return _tableCache.loadAll();
    }

    /**
    * update an JPO to database.
    * @return return true if updated successfully, otherwise return false
    */
    @Override
    public boolean update(){
        int __res = _tableCache.update(this, _updateSQL, 
            serverId, monetId);

        return (__res > 0);
    }

    /**
    * update JPO in batch.
    * @return num of records successfully updated.
    */
    public static int updateBatch(BTNoticationServer[] objList){
        Object[][] argv = new Object[objList.length][];

        for (int idx = 0; idx < objList.length; idx++){
            BTNoticationServer o = objList[idx];
            Object[] args = new Object[]{
                o.serverId, o.monetId};

            argv[idx] = args;
        }

        return _tableCache.updateBatch(objList, _updateSQL, argv);
    }

    /**
    * update JPO by QueryCriteria.
    * @return num of records successfully updated.
    */
    public static int updateByCriteria(TableBase.AttributeValue<?>[] valueList, QueryCriteria ...qcList){
        return _tableCache.updateByCriteria(valueList, qcList);
    }

    /**
    * remove an JPO from database and cache.
    * @return true if successfully removed, otherwise return false
    */
    @Override
    public boolean remove(){
        int __res = _tableCache.remove(this, _deleteSQL, monetId);
        return (__res > 0);
    }

    /**
    * remove JPOs in batch from database and cache.
    * @return num of records successfully removed.
    */
    public static int removeBatch(BTNoticationServer[] objList){
        Object argv[] = new Object[objList.length];

        for (int idx = 0; idx < objList.length; idx++){
            argv[idx] = objList[idx].monetId;
        }

        int res = _tableCache.removeBatch(objList, _deleteSQL, argv);
        return res;
    }

    /**
    * remove JPOs from database and cache by criteria.
    * @return num of records removed.
    */
    public static int removeByCriteria(QueryCriteria qc, QueryCriteria ...moreQcs){
        return _tableCache.removeByCriteria(qc, moreQcs);
    }

    /**
    * remove all JPOs from database and cache.
    * CAUTION: this operation is irrevocable.
    * @return num of records removed.
    */
    public static int __removeAll(){
        return _tableCache.removeAll();
    }

    /**
    * create a new JPO.<br>
    * If the a record with the same index in the cache is found,<br>
    * the cached object is return, and no DB record is created.<br>
    * Otherwise a new record is created and return, and a DB record is created.
    * @return an JPO if successfully created, null otherwise.
    */
    public static BTNoticationServer create(int monetId){

        BTNoticationServer __newObj = new BTNoticationServer(monetId);

        return (BTNoticationServer) _tableCache.create(__newObj, _createSQL, 
            __newObj.monetId, __newObj.serverId);
    }

    /**
    * Create a new JPO with initial values.<br>
    * Non-auto-incremental index is required<br>
    * If a field is set for more than one time<br>,
    * subsequent set will surpass preceding set.<br>
    * If the a record with the same index in the cache is found,<br>
    * the cached object is return, and no DB record is created.<br>
    * Otherwise a new record is created and return, and a DB record is created.
    * @return an JPO if successfully created, null otherwise.
    */
    public static BTNoticationServer create(int monetId, 
            TableBase.AttributeValue<?> attrVal,
            TableBase.AttributeValue<?>... attrVals){

        BTNoticationServer __newObj = new BTNoticationServer(monetId);

        if (null != attrVal.getVal()){
            __newObj._setValue(attrVal.getFidx(), attrVal.getVal());
        }

        for (TableBase.AttributeValue<?> attrV: attrVals){
            if (null != attrV.getVal()){
                __newObj._setValue(attrV.getFidx(), attrV.getVal());
            }
        }

        return (BTNoticationServer) _tableCache.create(__newObj, _createSQL, 
            __newObj.monetId, __newObj.serverId);
    }

    /**
    * find a JPO by indexes.
    * @return the found JPO or null
    */
    public static BTNoticationServer getOne(int monetId){
        return (BTNoticationServer) _tableCache.getOne(_genKey(monetId), _querySQL, monetId);
    }

    /**
    * find a JPO by arbitrary query criteria.
    * @return the found JPO or null
    */
    public static BTNoticationServer getOneByCriteria(QueryCriteria ...criteria){
        return (BTNoticationServer)_tableCache.getOneByCriteria(criteria);
    }

    /**
    * find all JPOs those match the query criteria list.
    * @return a list of JPO found.
    */
    public static ArrayList<BTNoticationServer> getManyByCriteria(QueryCriteria ...criteria){
        return _tableCache.getManyByCriteria(criteria);
    }

    /**
    * find a JPO by arbitrary SQL statement.
    * @return return the found JPO or null.
    */
    public static BTNoticationServer getOneBySQL(String sql, Object ...args){
        return (BTNoticationServer)_tableCache.getOneBySQL(sql, args);
    }

    /**
    * find all JPOs by arbitrary SQL statement.
    * @return a list of JPO found.
    */
    public static ArrayList<BTNoticationServer> getManayBySQL(String sql, Object ...args){
        return  _tableCache.getManyBySQL(sql, args);
    }

    /**
    * query objects from database by specified class Type
    * @return a list of OBJECT found.
    */
    public static <T> ArrayList<T> getManyByArbitarySQL(Class<T> clazz, String sql, Object[] args){
        return _tableCache._queryByArbitarySQL(clazz, sql, args);
    }

}
