// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history/bills.proto

package protocols.history;

public final class bills {
  private bills() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *语种，en_US为英文，zh_CN为中文。
     * </pre>
     *
     * <code>string lang = 1;</code>
     */
    java.lang.String getLang();
    /**
     * <pre>
     *语种，en_US为英文，zh_CN为中文。
     * </pre>
     *
     * <code>string lang = 1;</code>
     */
    com.google.protobuf.ByteString
        getLangBytes();

    /**
     * <pre>
     *cube=房卡账单 coin=金币账单
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     *cube=房卡账单 coin=金币账单
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * <pre>
   * 请求
   * </pre>
   *
   * Protobuf type {@code request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:request)
      requestOrBuilder {
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      lang_ = "";
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              lang_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.history.bills.internal_static_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.history.bills.internal_static_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.history.bills.request.class, protocols.history.bills.request.Builder.class);
    }

    public static final int LANG_FIELD_NUMBER = 1;
    private volatile java.lang.Object lang_;
    /**
     * <pre>
     *语种，en_US为英文，zh_CN为中文。
     * </pre>
     *
     * <code>string lang = 1;</code>
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *语种，en_US为英文，zh_CN为中文。
     * </pre>
     *
     * <code>string lang = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *cube=房卡账单 coin=金币账单
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *cube=房卡账单 coin=金币账单
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLangBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lang_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLangBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lang_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.history.bills.request)) {
        return super.equals(obj);
      }
      protocols.history.bills.request other = (protocols.history.bills.request) obj;

      boolean result = true;
      result = result && getLang()
          .equals(other.getLang());
      result = result && getType()
          .equals(other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LANG_FIELD_NUMBER;
      hash = (53 * hash) + getLang().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.history.bills.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.history.bills.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.history.bills.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求
     * </pre>
     *
     * Protobuf type {@code request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:request)
        protocols.history.bills.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.history.bills.internal_static_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.history.bills.internal_static_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.history.bills.request.class, protocols.history.bills.request.Builder.class);
      }

      // Construct using protocols.history.bills.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lang_ = "";

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.history.bills.internal_static_request_descriptor;
      }

      public protocols.history.bills.request getDefaultInstanceForType() {
        return protocols.history.bills.request.getDefaultInstance();
      }

      public protocols.history.bills.request build() {
        protocols.history.bills.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.history.bills.request buildPartial() {
        protocols.history.bills.request result = new protocols.history.bills.request(this);
        result.lang_ = lang_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.history.bills.request) {
          return mergeFrom((protocols.history.bills.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.history.bills.request other) {
        if (other == protocols.history.bills.request.getDefaultInstance()) return this;
        if (!other.getLang().isEmpty()) {
          lang_ = other.lang_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.history.bills.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.history.bills.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object lang_ = "";
      /**
       * <pre>
       *语种，en_US为英文，zh_CN为中文。
       * </pre>
       *
       * <code>string lang = 1;</code>
       */
      public java.lang.String getLang() {
        java.lang.Object ref = lang_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lang_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *语种，en_US为英文，zh_CN为中文。
       * </pre>
       *
       * <code>string lang = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLangBytes() {
        java.lang.Object ref = lang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *语种，en_US为英文，zh_CN为中文。
       * </pre>
       *
       * <code>string lang = 1;</code>
       */
      public Builder setLang(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lang_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语种，en_US为英文，zh_CN为中文。
       * </pre>
       *
       * <code>string lang = 1;</code>
       */
      public Builder clearLang() {
        
        lang_ = getDefaultInstance().getLang();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语种，en_US为英文，zh_CN为中文。
       * </pre>
       *
       * <code>string lang = 1;</code>
       */
      public Builder setLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lang_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *cube=房卡账单 coin=金币账单
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *cube=房卡账单 coin=金币账单
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *cube=房卡账单 coin=金币账单
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *cube=房卡账单 coin=金币账单
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *cube=房卡账单 coin=金币账单
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:request)
    }

    // @@protoc_insertion_point(class_scope:request)
    private static final protocols.history.bills.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.history.bills.request();
    }

    public static protocols.history.bills.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    public protocols.history.bills.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    java.util.List<protocols.history.bills.bill_t> 
        getBillsList();
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    protocols.history.bills.bill_t getBills(int index);
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    int getBillsCount();
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    java.util.List<? extends protocols.history.bills.bill_tOrBuilder> 
        getBillsOrBuilderList();
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    protocols.history.bills.bill_tOrBuilder getBillsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * Protobuf type {@code response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:response)
      responseOrBuilder {
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      bills_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                bills_ = new java.util.ArrayList<protocols.history.bills.bill_t>();
                mutable_bitField0_ |= 0x00000001;
              }
              bills_.add(
                  input.readMessage(protocols.history.bills.bill_t.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          bills_ = java.util.Collections.unmodifiableList(bills_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.history.bills.internal_static_response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.history.bills.internal_static_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.history.bills.response.class, protocols.history.bills.response.Builder.class);
    }

    public static final int BILLS_FIELD_NUMBER = 1;
    private java.util.List<protocols.history.bills.bill_t> bills_;
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    public java.util.List<protocols.history.bills.bill_t> getBillsList() {
      return bills_;
    }
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    public java.util.List<? extends protocols.history.bills.bill_tOrBuilder> 
        getBillsOrBuilderList() {
      return bills_;
    }
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    public int getBillsCount() {
      return bills_.size();
    }
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    public protocols.history.bills.bill_t getBills(int index) {
      return bills_.get(index);
    }
    /**
     * <pre>
     * 账单
     * </pre>
     *
     * <code>repeated .bill_t bills = 1;</code>
     */
    public protocols.history.bills.bill_tOrBuilder getBillsOrBuilder(
        int index) {
      return bills_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < bills_.size(); i++) {
        output.writeMessage(1, bills_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < bills_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bills_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.history.bills.response)) {
        return super.equals(obj);
      }
      protocols.history.bills.response other = (protocols.history.bills.response) obj;

      boolean result = true;
      result = result && getBillsList()
          .equals(other.getBillsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBillsCount() > 0) {
        hash = (37 * hash) + BILLS_FIELD_NUMBER;
        hash = (53 * hash) + getBillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.history.bills.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.history.bills.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.history.bills.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回
     * </pre>
     *
     * Protobuf type {@code response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response)
        protocols.history.bills.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.history.bills.internal_static_response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.history.bills.internal_static_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.history.bills.response.class, protocols.history.bills.response.Builder.class);
      }

      // Construct using protocols.history.bills.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBillsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (billsBuilder_ == null) {
          bills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          billsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.history.bills.internal_static_response_descriptor;
      }

      public protocols.history.bills.response getDefaultInstanceForType() {
        return protocols.history.bills.response.getDefaultInstance();
      }

      public protocols.history.bills.response build() {
        protocols.history.bills.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.history.bills.response buildPartial() {
        protocols.history.bills.response result = new protocols.history.bills.response(this);
        int from_bitField0_ = bitField0_;
        if (billsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bills_ = java.util.Collections.unmodifiableList(bills_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bills_ = bills_;
        } else {
          result.bills_ = billsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.history.bills.response) {
          return mergeFrom((protocols.history.bills.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.history.bills.response other) {
        if (other == protocols.history.bills.response.getDefaultInstance()) return this;
        if (billsBuilder_ == null) {
          if (!other.bills_.isEmpty()) {
            if (bills_.isEmpty()) {
              bills_ = other.bills_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBillsIsMutable();
              bills_.addAll(other.bills_);
            }
            onChanged();
          }
        } else {
          if (!other.bills_.isEmpty()) {
            if (billsBuilder_.isEmpty()) {
              billsBuilder_.dispose();
              billsBuilder_ = null;
              bills_ = other.bills_;
              bitField0_ = (bitField0_ & ~0x00000001);
              billsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBillsFieldBuilder() : null;
            } else {
              billsBuilder_.addAllMessages(other.bills_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.history.bills.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.history.bills.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protocols.history.bills.bill_t> bills_ =
        java.util.Collections.emptyList();
      private void ensureBillsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bills_ = new java.util.ArrayList<protocols.history.bills.bill_t>(bills_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.history.bills.bill_t, protocols.history.bills.bill_t.Builder, protocols.history.bills.bill_tOrBuilder> billsBuilder_;

      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public java.util.List<protocols.history.bills.bill_t> getBillsList() {
        if (billsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bills_);
        } else {
          return billsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public int getBillsCount() {
        if (billsBuilder_ == null) {
          return bills_.size();
        } else {
          return billsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public protocols.history.bills.bill_t getBills(int index) {
        if (billsBuilder_ == null) {
          return bills_.get(index);
        } else {
          return billsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder setBills(
          int index, protocols.history.bills.bill_t value) {
        if (billsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBillsIsMutable();
          bills_.set(index, value);
          onChanged();
        } else {
          billsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder setBills(
          int index, protocols.history.bills.bill_t.Builder builderForValue) {
        if (billsBuilder_ == null) {
          ensureBillsIsMutable();
          bills_.set(index, builderForValue.build());
          onChanged();
        } else {
          billsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder addBills(protocols.history.bills.bill_t value) {
        if (billsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBillsIsMutable();
          bills_.add(value);
          onChanged();
        } else {
          billsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder addBills(
          int index, protocols.history.bills.bill_t value) {
        if (billsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBillsIsMutable();
          bills_.add(index, value);
          onChanged();
        } else {
          billsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder addBills(
          protocols.history.bills.bill_t.Builder builderForValue) {
        if (billsBuilder_ == null) {
          ensureBillsIsMutable();
          bills_.add(builderForValue.build());
          onChanged();
        } else {
          billsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder addBills(
          int index, protocols.history.bills.bill_t.Builder builderForValue) {
        if (billsBuilder_ == null) {
          ensureBillsIsMutable();
          bills_.add(index, builderForValue.build());
          onChanged();
        } else {
          billsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder addAllBills(
          java.lang.Iterable<? extends protocols.history.bills.bill_t> values) {
        if (billsBuilder_ == null) {
          ensureBillsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bills_);
          onChanged();
        } else {
          billsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder clearBills() {
        if (billsBuilder_ == null) {
          bills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          billsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public Builder removeBills(int index) {
        if (billsBuilder_ == null) {
          ensureBillsIsMutable();
          bills_.remove(index);
          onChanged();
        } else {
          billsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public protocols.history.bills.bill_t.Builder getBillsBuilder(
          int index) {
        return getBillsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public protocols.history.bills.bill_tOrBuilder getBillsOrBuilder(
          int index) {
        if (billsBuilder_ == null) {
          return bills_.get(index);  } else {
          return billsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public java.util.List<? extends protocols.history.bills.bill_tOrBuilder> 
           getBillsOrBuilderList() {
        if (billsBuilder_ != null) {
          return billsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bills_);
        }
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public protocols.history.bills.bill_t.Builder addBillsBuilder() {
        return getBillsFieldBuilder().addBuilder(
            protocols.history.bills.bill_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public protocols.history.bills.bill_t.Builder addBillsBuilder(
          int index) {
        return getBillsFieldBuilder().addBuilder(
            index, protocols.history.bills.bill_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 账单
       * </pre>
       *
       * <code>repeated .bill_t bills = 1;</code>
       */
      public java.util.List<protocols.history.bills.bill_t.Builder> 
           getBillsBuilderList() {
        return getBillsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.history.bills.bill_t, protocols.history.bills.bill_t.Builder, protocols.history.bills.bill_tOrBuilder> 
          getBillsFieldBuilder() {
        if (billsBuilder_ == null) {
          billsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocols.history.bills.bill_t, protocols.history.bills.bill_t.Builder, protocols.history.bills.bill_tOrBuilder>(
                  bills_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bills_ = null;
        }
        return billsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:response)
    }

    // @@protoc_insertion_point(class_scope:response)
    private static final protocols.history.bills.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.history.bills.response();
    }

    public static protocols.history.bills.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    public protocols.history.bills.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface bill_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bill_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>string source = 1;</code>
     */
    java.lang.String getSource();
    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>string source = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <pre>
     * 来源描述
     * </pre>
     *
     * <code>string sourceDesc = 2;</code>
     */
    java.lang.String getSourceDesc();
    /**
     * <pre>
     * 来源描述
     * </pre>
     *
     * <code>string sourceDesc = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceDescBytes();

    /**
     * <pre>
     * 金额(负数代表消费)
     * </pre>
     *
     * <code>sint32 amount = 3;</code>
     */
    int getAmount();

    /**
     * <pre>
     * 之前余额
     * </pre>
     *
     * <code>uint32 beforeBal = 4;</code>
     */
    int getBeforeBal();

    /**
     * <pre>
     * 之后余额
     * </pre>
     *
     * <code>uint32 afterBal = 5;</code>
     */
    int getAfterBal();

    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>string datetime = 6;</code>
     */
    java.lang.String getDatetime();
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>string datetime = 6;</code>
     */
    com.google.protobuf.ByteString
        getDatetimeBytes();
  }
  /**
   * <pre>
   * 房卡账单数据
   * </pre>
   *
   * Protobuf type {@code bill_t}
   */
  public  static final class bill_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bill_t)
      bill_tOrBuilder {
    // Use bill_t.newBuilder() to construct.
    private bill_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private bill_t() {
      source_ = "";
      sourceDesc_ = "";
      amount_ = 0;
      beforeBal_ = 0;
      afterBal_ = 0;
      datetime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private bill_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sourceDesc_ = s;
              break;
            }
            case 24: {

              amount_ = input.readSInt32();
              break;
            }
            case 32: {

              beforeBal_ = input.readUInt32();
              break;
            }
            case 40: {

              afterBal_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              datetime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.history.bills.internal_static_bill_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.history.bills.internal_static_bill_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.history.bills.bill_t.class, protocols.history.bills.bill_t.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object source_;
    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>string source = 1;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>string source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEDESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object sourceDesc_;
    /**
     * <pre>
     * 来源描述
     * </pre>
     *
     * <code>string sourceDesc = 2;</code>
     */
    public java.lang.String getSourceDesc() {
      java.lang.Object ref = sourceDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceDesc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 来源描述
     * </pre>
     *
     * <code>string sourceDesc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDescBytes() {
      java.lang.Object ref = sourceDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    /**
     * <pre>
     * 金额(负数代表消费)
     * </pre>
     *
     * <code>sint32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int BEFOREBAL_FIELD_NUMBER = 4;
    private int beforeBal_;
    /**
     * <pre>
     * 之前余额
     * </pre>
     *
     * <code>uint32 beforeBal = 4;</code>
     */
    public int getBeforeBal() {
      return beforeBal_;
    }

    public static final int AFTERBAL_FIELD_NUMBER = 5;
    private int afterBal_;
    /**
     * <pre>
     * 之后余额
     * </pre>
     *
     * <code>uint32 afterBal = 5;</code>
     */
    public int getAfterBal() {
      return afterBal_;
    }

    public static final int DATETIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object datetime_;
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>string datetime = 6;</code>
     */
    public java.lang.String getDatetime() {
      java.lang.Object ref = datetime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datetime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 时间
     * </pre>
     *
     * <code>string datetime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDatetimeBytes() {
      java.lang.Object ref = datetime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, source_);
      }
      if (!getSourceDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceDesc_);
      }
      if (amount_ != 0) {
        output.writeSInt32(3, amount_);
      }
      if (beforeBal_ != 0) {
        output.writeUInt32(4, beforeBal_);
      }
      if (afterBal_ != 0) {
        output.writeUInt32(5, afterBal_);
      }
      if (!getDatetimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, datetime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, source_);
      }
      if (!getSourceDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceDesc_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, amount_);
      }
      if (beforeBal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, beforeBal_);
      }
      if (afterBal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, afterBal_);
      }
      if (!getDatetimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, datetime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.history.bills.bill_t)) {
        return super.equals(obj);
      }
      protocols.history.bills.bill_t other = (protocols.history.bills.bill_t) obj;

      boolean result = true;
      result = result && getSource()
          .equals(other.getSource());
      result = result && getSourceDesc()
          .equals(other.getSourceDesc());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getBeforeBal()
          == other.getBeforeBal());
      result = result && (getAfterBal()
          == other.getAfterBal());
      result = result && getDatetime()
          .equals(other.getDatetime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + SOURCEDESC_FIELD_NUMBER;
      hash = (53 * hash) + getSourceDesc().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + BEFOREBAL_FIELD_NUMBER;
      hash = (53 * hash) + getBeforeBal();
      hash = (37 * hash) + AFTERBAL_FIELD_NUMBER;
      hash = (53 * hash) + getAfterBal();
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDatetime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.history.bills.bill_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.bill_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.bill_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.history.bills.bill_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.history.bills.bill_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.bill_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.bill_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.history.bills.bill_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.history.bills.bill_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.history.bills.bill_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.history.bills.bill_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 房卡账单数据
     * </pre>
     *
     * Protobuf type {@code bill_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bill_t)
        protocols.history.bills.bill_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.history.bills.internal_static_bill_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.history.bills.internal_static_bill_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.history.bills.bill_t.class, protocols.history.bills.bill_t.Builder.class);
      }

      // Construct using protocols.history.bills.bill_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = "";

        sourceDesc_ = "";

        amount_ = 0;

        beforeBal_ = 0;

        afterBal_ = 0;

        datetime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.history.bills.internal_static_bill_t_descriptor;
      }

      public protocols.history.bills.bill_t getDefaultInstanceForType() {
        return protocols.history.bills.bill_t.getDefaultInstance();
      }

      public protocols.history.bills.bill_t build() {
        protocols.history.bills.bill_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.history.bills.bill_t buildPartial() {
        protocols.history.bills.bill_t result = new protocols.history.bills.bill_t(this);
        result.source_ = source_;
        result.sourceDesc_ = sourceDesc_;
        result.amount_ = amount_;
        result.beforeBal_ = beforeBal_;
        result.afterBal_ = afterBal_;
        result.datetime_ = datetime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.history.bills.bill_t) {
          return mergeFrom((protocols.history.bills.bill_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.history.bills.bill_t other) {
        if (other == protocols.history.bills.bill_t.getDefaultInstance()) return this;
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (!other.getSourceDesc().isEmpty()) {
          sourceDesc_ = other.sourceDesc_;
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.getBeforeBal() != 0) {
          setBeforeBal(other.getBeforeBal());
        }
        if (other.getAfterBal() != 0) {
          setAfterBal(other.getAfterBal());
        }
        if (!other.getDatetime().isEmpty()) {
          datetime_ = other.datetime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.history.bills.bill_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.history.bills.bill_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>string source = 1;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>string source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>string source = 1;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>string source = 1;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>string source = 1;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceDesc_ = "";
      /**
       * <pre>
       * 来源描述
       * </pre>
       *
       * <code>string sourceDesc = 2;</code>
       */
      public java.lang.String getSourceDesc() {
        java.lang.Object ref = sourceDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 来源描述
       * </pre>
       *
       * <code>string sourceDesc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceDescBytes() {
        java.lang.Object ref = sourceDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 来源描述
       * </pre>
       *
       * <code>string sourceDesc = 2;</code>
       */
      public Builder setSourceDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源描述
       * </pre>
       *
       * <code>string sourceDesc = 2;</code>
       */
      public Builder clearSourceDesc() {
        
        sourceDesc_ = getDefaultInstance().getSourceDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源描述
       * </pre>
       *
       * <code>string sourceDesc = 2;</code>
       */
      public Builder setSourceDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourceDesc_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <pre>
       * 金额(负数代表消费)
       * </pre>
       *
       * <code>sint32 amount = 3;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * 金额(负数代表消费)
       * </pre>
       *
       * <code>sint32 amount = 3;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 金额(负数代表消费)
       * </pre>
       *
       * <code>sint32 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private int beforeBal_ ;
      /**
       * <pre>
       * 之前余额
       * </pre>
       *
       * <code>uint32 beforeBal = 4;</code>
       */
      public int getBeforeBal() {
        return beforeBal_;
      }
      /**
       * <pre>
       * 之前余额
       * </pre>
       *
       * <code>uint32 beforeBal = 4;</code>
       */
      public Builder setBeforeBal(int value) {
        
        beforeBal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 之前余额
       * </pre>
       *
       * <code>uint32 beforeBal = 4;</code>
       */
      public Builder clearBeforeBal() {
        
        beforeBal_ = 0;
        onChanged();
        return this;
      }

      private int afterBal_ ;
      /**
       * <pre>
       * 之后余额
       * </pre>
       *
       * <code>uint32 afterBal = 5;</code>
       */
      public int getAfterBal() {
        return afterBal_;
      }
      /**
       * <pre>
       * 之后余额
       * </pre>
       *
       * <code>uint32 afterBal = 5;</code>
       */
      public Builder setAfterBal(int value) {
        
        afterBal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 之后余额
       * </pre>
       *
       * <code>uint32 afterBal = 5;</code>
       */
      public Builder clearAfterBal() {
        
        afterBal_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object datetime_ = "";
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>string datetime = 6;</code>
       */
      public java.lang.String getDatetime() {
        java.lang.Object ref = datetime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          datetime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>string datetime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDatetimeBytes() {
        java.lang.Object ref = datetime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datetime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>string datetime = 6;</code>
       */
      public Builder setDatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        datetime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>string datetime = 6;</code>
       */
      public Builder clearDatetime() {
        
        datetime_ = getDefaultInstance().getDatetime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间
       * </pre>
       *
       * <code>string datetime = 6;</code>
       */
      public Builder setDatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        datetime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bill_t)
    }

    // @@protoc_insertion_point(class_scope:bill_t)
    private static final protocols.history.bills.bill_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.history.bills.bill_t();
    }

    public static protocols.history.bills.bill_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<bill_t>
        PARSER = new com.google.protobuf.AbstractParser<bill_t>() {
      public bill_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new bill_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<bill_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<bill_t> getParserForType() {
      return PARSER;
    }

    public protocols.history.bills.bill_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bill_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bill_t_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023history/bills.proto\"%\n\007request\022\014\n\004lang" +
      "\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\"\"\n\010response\022\026\n\005bill" +
      "s\030\001 \003(\0132\007.bill_t\"s\n\006bill_t\022\016\n\006source\030\001 \001" +
      "(\t\022\022\n\nsourceDesc\030\002 \001(\t\022\016\n\006amount\030\003 \001(\021\022\021" +
      "\n\tbeforeBal\030\004 \001(\r\022\020\n\010afterBal\030\005 \001(\r\022\020\n\010d" +
      "atetime\030\006 \001(\tB\032\n\021protocols.historyB\005bill" +
      "sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { "Lang", "Type", });
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Bills", });
    internal_static_bill_t_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bill_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bill_t_descriptor,
        new java.lang.String[] { "Source", "SourceDesc", "Amount", "BeforeBal", "AfterBal", "Datetime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
