// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/checkupdate.proto

package protocols.user;

public final class checkupdate {
  private checkupdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 平台，0=未知 1=iOS 2=Android
     * </pre>
     *
     * <code>uint32 platform = 1;</code>
     */
    int getPlatform();

    /**
     * <pre>
     * 客户端版本号
     * </pre>
     *
     * <code>string app_ver = 2;</code>
     */
    java.lang.String getAppVer();
    /**
     * <pre>
     * 客户端版本号
     * </pre>
     *
     * <code>string app_ver = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppVerBytes();
  }
  /**
   * <pre>
   * 请求
   * </pre>
   *
   * Protobuf type {@code request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:request)
      requestOrBuilder {
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      platform_ = 0;
      appVer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              platform_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appVer_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.user.checkupdate.internal_static_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.user.checkupdate.internal_static_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.user.checkupdate.request.class, protocols.user.checkupdate.request.Builder.class);
    }

    public static final int PLATFORM_FIELD_NUMBER = 1;
    private int platform_;
    /**
     * <pre>
     * 平台，0=未知 1=iOS 2=Android
     * </pre>
     *
     * <code>uint32 platform = 1;</code>
     */
    public int getPlatform() {
      return platform_;
    }

    public static final int APP_VER_FIELD_NUMBER = 2;
    private volatile java.lang.Object appVer_;
    /**
     * <pre>
     * 客户端版本号
     * </pre>
     *
     * <code>string app_ver = 2;</code>
     */
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端版本号
     * </pre>
     *
     * <code>string app_ver = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (platform_ != 0) {
        output.writeUInt32(1, platform_);
      }
      if (!getAppVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appVer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (platform_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, platform_);
      }
      if (!getAppVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appVer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.user.checkupdate.request)) {
        return super.equals(obj);
      }
      protocols.user.checkupdate.request other = (protocols.user.checkupdate.request) obj;

      boolean result = true;
      result = result && (getPlatform()
          == other.getPlatform());
      result = result && getAppVer()
          .equals(other.getAppVer());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform();
      hash = (37 * hash) + APP_VER_FIELD_NUMBER;
      hash = (53 * hash) + getAppVer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.user.checkupdate.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.user.checkupdate.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.user.checkupdate.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.user.checkupdate.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.user.checkupdate.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.user.checkupdate.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.user.checkupdate.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.user.checkupdate.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求
     * </pre>
     *
     * Protobuf type {@code request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:request)
        protocols.user.checkupdate.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.user.checkupdate.internal_static_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.user.checkupdate.internal_static_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.user.checkupdate.request.class, protocols.user.checkupdate.request.Builder.class);
      }

      // Construct using protocols.user.checkupdate.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        platform_ = 0;

        appVer_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.user.checkupdate.internal_static_request_descriptor;
      }

      public protocols.user.checkupdate.request getDefaultInstanceForType() {
        return protocols.user.checkupdate.request.getDefaultInstance();
      }

      public protocols.user.checkupdate.request build() {
        protocols.user.checkupdate.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.user.checkupdate.request buildPartial() {
        protocols.user.checkupdate.request result = new protocols.user.checkupdate.request(this);
        result.platform_ = platform_;
        result.appVer_ = appVer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.user.checkupdate.request) {
          return mergeFrom((protocols.user.checkupdate.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.user.checkupdate.request other) {
        if (other == protocols.user.checkupdate.request.getDefaultInstance()) return this;
        if (other.getPlatform() != 0) {
          setPlatform(other.getPlatform());
        }
        if (!other.getAppVer().isEmpty()) {
          appVer_ = other.appVer_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.user.checkupdate.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.user.checkupdate.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int platform_ ;
      /**
       * <pre>
       * 平台，0=未知 1=iOS 2=Android
       * </pre>
       *
       * <code>uint32 platform = 1;</code>
       */
      public int getPlatform() {
        return platform_;
      }
      /**
       * <pre>
       * 平台，0=未知 1=iOS 2=Android
       * </pre>
       *
       * <code>uint32 platform = 1;</code>
       */
      public Builder setPlatform(int value) {
        
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平台，0=未知 1=iOS 2=Android
       * </pre>
       *
       * <code>uint32 platform = 1;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <pre>
       * 客户端版本号
       * </pre>
       *
       * <code>string app_ver = 2;</code>
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 客户端版本号
       * </pre>
       *
       * <code>string app_ver = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端版本号
       * </pre>
       *
       * <code>string app_ver = 2;</code>
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端版本号
       * </pre>
       *
       * <code>string app_ver = 2;</code>
       */
      public Builder clearAppVer() {
        
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端版本号
       * </pre>
       *
       * <code>string app_ver = 2;</code>
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVer_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:request)
    }

    // @@protoc_insertion_point(class_scope:request)
    private static final protocols.user.checkupdate.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.user.checkupdate.request();
    }

    public static protocols.user.checkupdate.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    public protocols.user.checkupdate.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误代码，0=成功
     * </pre>
     *
     * <code>sint32 error = 1;</code>
     */
    int getError();

    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    java.lang.String getErrDesc();
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrDescBytes();

    /**
     * <pre>
     * 是否需要更新
     * </pre>
     *
     * <code>bool needUpdate = 3;</code>
     */
    boolean getNeedUpdate();

    /**
     * <pre>
     * 客户端最新版本
     * </pre>
     *
     * <code>string latestVer = 4;</code>
     */
    java.lang.String getLatestVer();
    /**
     * <pre>
     * 客户端最新版本
     * </pre>
     *
     * <code>string latestVer = 4;</code>
     */
    com.google.protobuf.ByteString
        getLatestVerBytes();

    /**
     * <pre>
     * 应用下载地址
     * </pre>
     *
     * <code>string appUrl = 5;</code>
     */
    java.lang.String getAppUrl();
    /**
     * <pre>
     * 应用下载地址
     * </pre>
     *
     * <code>string appUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getAppUrlBytes();
  }
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * Protobuf type {@code response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:response)
      responseOrBuilder {
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      error_ = 0;
      errDesc_ = "";
      needUpdate_ = false;
      latestVer_ = "";
      appUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              error_ = input.readSInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              errDesc_ = s;
              break;
            }
            case 24: {

              needUpdate_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              latestVer_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              appUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.user.checkupdate.internal_static_response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.user.checkupdate.internal_static_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.user.checkupdate.response.class, protocols.user.checkupdate.response.Builder.class);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_;
    /**
     * <pre>
     * 错误代码，0=成功
     * </pre>
     *
     * <code>sint32 error = 1;</code>
     */
    public int getError() {
      return error_;
    }

    public static final int ERRDESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object errDesc_;
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    public java.lang.String getErrDesc() {
      java.lang.Object ref = errDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errDesc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrDescBytes() {
      java.lang.Object ref = errDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEEDUPDATE_FIELD_NUMBER = 3;
    private boolean needUpdate_;
    /**
     * <pre>
     * 是否需要更新
     * </pre>
     *
     * <code>bool needUpdate = 3;</code>
     */
    public boolean getNeedUpdate() {
      return needUpdate_;
    }

    public static final int LATESTVER_FIELD_NUMBER = 4;
    private volatile java.lang.Object latestVer_;
    /**
     * <pre>
     * 客户端最新版本
     * </pre>
     *
     * <code>string latestVer = 4;</code>
     */
    public java.lang.String getLatestVer() {
      java.lang.Object ref = latestVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latestVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 客户端最新版本
     * </pre>
     *
     * <code>string latestVer = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLatestVerBytes() {
      java.lang.Object ref = latestVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latestVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object appUrl_;
    /**
     * <pre>
     * 应用下载地址
     * </pre>
     *
     * <code>string appUrl = 5;</code>
     */
    public java.lang.String getAppUrl() {
      java.lang.Object ref = appUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 应用下载地址
     * </pre>
     *
     * <code>string appUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppUrlBytes() {
      java.lang.Object ref = appUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != 0) {
        output.writeSInt32(1, error_);
      }
      if (!getErrDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errDesc_);
      }
      if (needUpdate_ != false) {
        output.writeBool(3, needUpdate_);
      }
      if (!getLatestVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, latestVer_);
      }
      if (!getAppUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, error_);
      }
      if (!getErrDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errDesc_);
      }
      if (needUpdate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, needUpdate_);
      }
      if (!getLatestVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, latestVer_);
      }
      if (!getAppUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.user.checkupdate.response)) {
        return super.equals(obj);
      }
      protocols.user.checkupdate.response other = (protocols.user.checkupdate.response) obj;

      boolean result = true;
      result = result && (getError()
          == other.getError());
      result = result && getErrDesc()
          .equals(other.getErrDesc());
      result = result && (getNeedUpdate()
          == other.getNeedUpdate());
      result = result && getLatestVer()
          .equals(other.getLatestVer());
      result = result && getAppUrl()
          .equals(other.getAppUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError();
      hash = (37 * hash) + ERRDESC_FIELD_NUMBER;
      hash = (53 * hash) + getErrDesc().hashCode();
      hash = (37 * hash) + NEEDUPDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedUpdate());
      hash = (37 * hash) + LATESTVER_FIELD_NUMBER;
      hash = (53 * hash) + getLatestVer().hashCode();
      hash = (37 * hash) + APPURL_FIELD_NUMBER;
      hash = (53 * hash) + getAppUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.user.checkupdate.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.user.checkupdate.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.user.checkupdate.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.user.checkupdate.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.user.checkupdate.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.user.checkupdate.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.user.checkupdate.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.user.checkupdate.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.user.checkupdate.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回
     * </pre>
     *
     * Protobuf type {@code response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response)
        protocols.user.checkupdate.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.user.checkupdate.internal_static_response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.user.checkupdate.internal_static_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.user.checkupdate.response.class, protocols.user.checkupdate.response.Builder.class);
      }

      // Construct using protocols.user.checkupdate.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        error_ = 0;

        errDesc_ = "";

        needUpdate_ = false;

        latestVer_ = "";

        appUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.user.checkupdate.internal_static_response_descriptor;
      }

      public protocols.user.checkupdate.response getDefaultInstanceForType() {
        return protocols.user.checkupdate.response.getDefaultInstance();
      }

      public protocols.user.checkupdate.response build() {
        protocols.user.checkupdate.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.user.checkupdate.response buildPartial() {
        protocols.user.checkupdate.response result = new protocols.user.checkupdate.response(this);
        result.error_ = error_;
        result.errDesc_ = errDesc_;
        result.needUpdate_ = needUpdate_;
        result.latestVer_ = latestVer_;
        result.appUrl_ = appUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.user.checkupdate.response) {
          return mergeFrom((protocols.user.checkupdate.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.user.checkupdate.response other) {
        if (other == protocols.user.checkupdate.response.getDefaultInstance()) return this;
        if (other.getError() != 0) {
          setError(other.getError());
        }
        if (!other.getErrDesc().isEmpty()) {
          errDesc_ = other.errDesc_;
          onChanged();
        }
        if (other.getNeedUpdate() != false) {
          setNeedUpdate(other.getNeedUpdate());
        }
        if (!other.getLatestVer().isEmpty()) {
          latestVer_ = other.latestVer_;
          onChanged();
        }
        if (!other.getAppUrl().isEmpty()) {
          appUrl_ = other.appUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.user.checkupdate.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.user.checkupdate.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int error_ ;
      /**
       * <pre>
       * 错误代码，0=成功
       * </pre>
       *
       * <code>sint32 error = 1;</code>
       */
      public int getError() {
        return error_;
      }
      /**
       * <pre>
       * 错误代码，0=成功
       * </pre>
       *
       * <code>sint32 error = 1;</code>
       */
      public Builder setError(int value) {
        
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误代码，0=成功
       * </pre>
       *
       * <code>sint32 error = 1;</code>
       */
      public Builder clearError() {
        
        error_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errDesc_ = "";
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public java.lang.String getErrDesc() {
        java.lang.Object ref = errDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrDescBytes() {
        java.lang.Object ref = errDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder setErrDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder clearErrDesc() {
        
        errDesc_ = getDefaultInstance().getErrDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder setErrDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errDesc_ = value;
        onChanged();
        return this;
      }

      private boolean needUpdate_ ;
      /**
       * <pre>
       * 是否需要更新
       * </pre>
       *
       * <code>bool needUpdate = 3;</code>
       */
      public boolean getNeedUpdate() {
        return needUpdate_;
      }
      /**
       * <pre>
       * 是否需要更新
       * </pre>
       *
       * <code>bool needUpdate = 3;</code>
       */
      public Builder setNeedUpdate(boolean value) {
        
        needUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否需要更新
       * </pre>
       *
       * <code>bool needUpdate = 3;</code>
       */
      public Builder clearNeedUpdate() {
        
        needUpdate_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object latestVer_ = "";
      /**
       * <pre>
       * 客户端最新版本
       * </pre>
       *
       * <code>string latestVer = 4;</code>
       */
      public java.lang.String getLatestVer() {
        java.lang.Object ref = latestVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latestVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 客户端最新版本
       * </pre>
       *
       * <code>string latestVer = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLatestVerBytes() {
        java.lang.Object ref = latestVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latestVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 客户端最新版本
       * </pre>
       *
       * <code>string latestVer = 4;</code>
       */
      public Builder setLatestVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        latestVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端最新版本
       * </pre>
       *
       * <code>string latestVer = 4;</code>
       */
      public Builder clearLatestVer() {
        
        latestVer_ = getDefaultInstance().getLatestVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端最新版本
       * </pre>
       *
       * <code>string latestVer = 4;</code>
       */
      public Builder setLatestVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        latestVer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appUrl_ = "";
      /**
       * <pre>
       * 应用下载地址
       * </pre>
       *
       * <code>string appUrl = 5;</code>
       */
      public java.lang.String getAppUrl() {
        java.lang.Object ref = appUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 应用下载地址
       * </pre>
       *
       * <code>string appUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppUrlBytes() {
        java.lang.Object ref = appUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 应用下载地址
       * </pre>
       *
       * <code>string appUrl = 5;</code>
       */
      public Builder setAppUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用下载地址
       * </pre>
       *
       * <code>string appUrl = 5;</code>
       */
      public Builder clearAppUrl() {
        
        appUrl_ = getDefaultInstance().getAppUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 应用下载地址
       * </pre>
       *
       * <code>string appUrl = 5;</code>
       */
      public Builder setAppUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:response)
    }

    // @@protoc_insertion_point(class_scope:response)
    private static final protocols.user.checkupdate.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.user.checkupdate.response();
    }

    public static protocols.user.checkupdate.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    public protocols.user.checkupdate.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026user/checkupdate.proto\",\n\007request\022\020\n\010p" +
      "latform\030\001 \001(\r\022\017\n\007app_ver\030\002 \001(\t\"a\n\010respon" +
      "se\022\r\n\005error\030\001 \001(\021\022\017\n\007errDesc\030\002 \001(\t\022\022\n\nne" +
      "edUpdate\030\003 \001(\010\022\021\n\tlatestVer\030\004 \001(\t\022\016\n\006app" +
      "Url\030\005 \001(\tB\035\n\016protocols.userB\013checkupdate" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { "Platform", "AppVer", });
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Error", "ErrDesc", "NeedUpdate", "LatestVer", "AppUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
