// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bull/over.proto

package protocols.bull;

public final class over {
  private over() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 局数
     * </pre>
     *
     * <code>required uint32 inning = 1;</code>
     */
    boolean hasInning();
    /**
     * <pre>
     * 局数
     * </pre>
     *
     * <code>required uint32 inning = 1;</code>
     */
    int getInning();

    /**
     * <pre>
     * 庄家
     * </pre>
     *
     * <code>required uint32 dealer = 2;</code>
     */
    boolean hasDealer();
    /**
     * <pre>
     * 庄家
     * </pre>
     *
     * <code>required uint32 dealer = 2;</code>
     */
    int getDealer();

    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    java.util.List<protocols.bull.over.seat_t> 
        getSeatsList();
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    protocols.bull.over.seat_t getSeats(int index);
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    int getSeatsCount();
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    java.util.List<? extends protocols.bull.over.seat_tOrBuilder> 
        getSeatsOrBuilderList();
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    protocols.bull.over.seat_tOrBuilder getSeatsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回
   * </pre>
   *
   * Protobuf type {@code response}
   */
  public  static final class response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:response)
      responseOrBuilder {
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private response() {
      inning_ = 0;
      dealer_ = 0;
      seats_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              inning_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dealer_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                seats_ = new java.util.ArrayList<protocols.bull.over.seat_t>();
                mutable_bitField0_ |= 0x00000004;
              }
              seats_.add(
                  input.readMessage(protocols.bull.over.seat_t.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          seats_ = java.util.Collections.unmodifiableList(seats_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.bull.over.internal_static_response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.bull.over.internal_static_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.bull.over.response.class, protocols.bull.over.response.Builder.class);
    }

    private int bitField0_;
    public static final int INNING_FIELD_NUMBER = 1;
    private int inning_;
    /**
     * <pre>
     * 局数
     * </pre>
     *
     * <code>required uint32 inning = 1;</code>
     */
    public boolean hasInning() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 局数
     * </pre>
     *
     * <code>required uint32 inning = 1;</code>
     */
    public int getInning() {
      return inning_;
    }

    public static final int DEALER_FIELD_NUMBER = 2;
    private int dealer_;
    /**
     * <pre>
     * 庄家
     * </pre>
     *
     * <code>required uint32 dealer = 2;</code>
     */
    public boolean hasDealer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 庄家
     * </pre>
     *
     * <code>required uint32 dealer = 2;</code>
     */
    public int getDealer() {
      return dealer_;
    }

    public static final int SEATS_FIELD_NUMBER = 3;
    private java.util.List<protocols.bull.over.seat_t> seats_;
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    public java.util.List<protocols.bull.over.seat_t> getSeatsList() {
      return seats_;
    }
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    public java.util.List<? extends protocols.bull.over.seat_tOrBuilder> 
        getSeatsOrBuilderList() {
      return seats_;
    }
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    public int getSeatsCount() {
      return seats_.size();
    }
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    public protocols.bull.over.seat_t getSeats(int index) {
      return seats_.get(index);
    }
    /**
     * <pre>
     * 座位信息
     * </pre>
     *
     * <code>repeated .seat_t seats = 3;</code>
     */
    public protocols.bull.over.seat_tOrBuilder getSeatsOrBuilder(
        int index) {
      return seats_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInning()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDealer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSeatsCount(); i++) {
        if (!getSeats(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, inning_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, dealer_);
      }
      for (int i = 0; i < seats_.size(); i++) {
        output.writeMessage(3, seats_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, inning_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, dealer_);
      }
      for (int i = 0; i < seats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, seats_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.bull.over.response)) {
        return super.equals(obj);
      }
      protocols.bull.over.response other = (protocols.bull.over.response) obj;

      boolean result = true;
      result = result && (hasInning() == other.hasInning());
      if (hasInning()) {
        result = result && (getInning()
            == other.getInning());
      }
      result = result && (hasDealer() == other.hasDealer());
      if (hasDealer()) {
        result = result && (getDealer()
            == other.getDealer());
      }
      result = result && getSeatsList()
          .equals(other.getSeatsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInning()) {
        hash = (37 * hash) + INNING_FIELD_NUMBER;
        hash = (53 * hash) + getInning();
      }
      if (hasDealer()) {
        hash = (37 * hash) + DEALER_FIELD_NUMBER;
        hash = (53 * hash) + getDealer();
      }
      if (getSeatsCount() > 0) {
        hash = (37 * hash) + SEATS_FIELD_NUMBER;
        hash = (53 * hash) + getSeatsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.bull.over.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.bull.over.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.bull.over.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.bull.over.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.bull.over.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.bull.over.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.bull.over.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.bull.over.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.bull.over.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.bull.over.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.bull.over.response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回
     * </pre>
     *
     * Protobuf type {@code response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response)
        protocols.bull.over.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.bull.over.internal_static_response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.bull.over.internal_static_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.bull.over.response.class, protocols.bull.over.response.Builder.class);
      }

      // Construct using protocols.bull.over.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSeatsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        inning_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dealer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (seatsBuilder_ == null) {
          seats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          seatsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.bull.over.internal_static_response_descriptor;
      }

      public protocols.bull.over.response getDefaultInstanceForType() {
        return protocols.bull.over.response.getDefaultInstance();
      }

      public protocols.bull.over.response build() {
        protocols.bull.over.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.bull.over.response buildPartial() {
        protocols.bull.over.response result = new protocols.bull.over.response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.inning_ = inning_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dealer_ = dealer_;
        if (seatsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            seats_ = java.util.Collections.unmodifiableList(seats_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.seats_ = seats_;
        } else {
          result.seats_ = seatsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.bull.over.response) {
          return mergeFrom((protocols.bull.over.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.bull.over.response other) {
        if (other == protocols.bull.over.response.getDefaultInstance()) return this;
        if (other.hasInning()) {
          setInning(other.getInning());
        }
        if (other.hasDealer()) {
          setDealer(other.getDealer());
        }
        if (seatsBuilder_ == null) {
          if (!other.seats_.isEmpty()) {
            if (seats_.isEmpty()) {
              seats_ = other.seats_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSeatsIsMutable();
              seats_.addAll(other.seats_);
            }
            onChanged();
          }
        } else {
          if (!other.seats_.isEmpty()) {
            if (seatsBuilder_.isEmpty()) {
              seatsBuilder_.dispose();
              seatsBuilder_ = null;
              seats_ = other.seats_;
              bitField0_ = (bitField0_ & ~0x00000004);
              seatsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSeatsFieldBuilder() : null;
            } else {
              seatsBuilder_.addAllMessages(other.seats_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInning()) {
          return false;
        }
        if (!hasDealer()) {
          return false;
        }
        for (int i = 0; i < getSeatsCount(); i++) {
          if (!getSeats(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.bull.over.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.bull.over.response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int inning_ ;
      /**
       * <pre>
       * 局数
       * </pre>
       *
       * <code>required uint32 inning = 1;</code>
       */
      public boolean hasInning() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 局数
       * </pre>
       *
       * <code>required uint32 inning = 1;</code>
       */
      public int getInning() {
        return inning_;
      }
      /**
       * <pre>
       * 局数
       * </pre>
       *
       * <code>required uint32 inning = 1;</code>
       */
      public Builder setInning(int value) {
        bitField0_ |= 0x00000001;
        inning_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 局数
       * </pre>
       *
       * <code>required uint32 inning = 1;</code>
       */
      public Builder clearInning() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inning_ = 0;
        onChanged();
        return this;
      }

      private int dealer_ ;
      /**
       * <pre>
       * 庄家
       * </pre>
       *
       * <code>required uint32 dealer = 2;</code>
       */
      public boolean hasDealer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 庄家
       * </pre>
       *
       * <code>required uint32 dealer = 2;</code>
       */
      public int getDealer() {
        return dealer_;
      }
      /**
       * <pre>
       * 庄家
       * </pre>
       *
       * <code>required uint32 dealer = 2;</code>
       */
      public Builder setDealer(int value) {
        bitField0_ |= 0x00000002;
        dealer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 庄家
       * </pre>
       *
       * <code>required uint32 dealer = 2;</code>
       */
      public Builder clearDealer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dealer_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protocols.bull.over.seat_t> seats_ =
        java.util.Collections.emptyList();
      private void ensureSeatsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          seats_ = new java.util.ArrayList<protocols.bull.over.seat_t>(seats_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.bull.over.seat_t, protocols.bull.over.seat_t.Builder, protocols.bull.over.seat_tOrBuilder> seatsBuilder_;

      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public java.util.List<protocols.bull.over.seat_t> getSeatsList() {
        if (seatsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(seats_);
        } else {
          return seatsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public int getSeatsCount() {
        if (seatsBuilder_ == null) {
          return seats_.size();
        } else {
          return seatsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public protocols.bull.over.seat_t getSeats(int index) {
        if (seatsBuilder_ == null) {
          return seats_.get(index);
        } else {
          return seatsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder setSeats(
          int index, protocols.bull.over.seat_t value) {
        if (seatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatsIsMutable();
          seats_.set(index, value);
          onChanged();
        } else {
          seatsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder setSeats(
          int index, protocols.bull.over.seat_t.Builder builderForValue) {
        if (seatsBuilder_ == null) {
          ensureSeatsIsMutable();
          seats_.set(index, builderForValue.build());
          onChanged();
        } else {
          seatsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder addSeats(protocols.bull.over.seat_t value) {
        if (seatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatsIsMutable();
          seats_.add(value);
          onChanged();
        } else {
          seatsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder addSeats(
          int index, protocols.bull.over.seat_t value) {
        if (seatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatsIsMutable();
          seats_.add(index, value);
          onChanged();
        } else {
          seatsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder addSeats(
          protocols.bull.over.seat_t.Builder builderForValue) {
        if (seatsBuilder_ == null) {
          ensureSeatsIsMutable();
          seats_.add(builderForValue.build());
          onChanged();
        } else {
          seatsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder addSeats(
          int index, protocols.bull.over.seat_t.Builder builderForValue) {
        if (seatsBuilder_ == null) {
          ensureSeatsIsMutable();
          seats_.add(index, builderForValue.build());
          onChanged();
        } else {
          seatsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder addAllSeats(
          java.lang.Iterable<? extends protocols.bull.over.seat_t> values) {
        if (seatsBuilder_ == null) {
          ensureSeatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, seats_);
          onChanged();
        } else {
          seatsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder clearSeats() {
        if (seatsBuilder_ == null) {
          seats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          seatsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public Builder removeSeats(int index) {
        if (seatsBuilder_ == null) {
          ensureSeatsIsMutable();
          seats_.remove(index);
          onChanged();
        } else {
          seatsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public protocols.bull.over.seat_t.Builder getSeatsBuilder(
          int index) {
        return getSeatsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public protocols.bull.over.seat_tOrBuilder getSeatsOrBuilder(
          int index) {
        if (seatsBuilder_ == null) {
          return seats_.get(index);  } else {
          return seatsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public java.util.List<? extends protocols.bull.over.seat_tOrBuilder> 
           getSeatsOrBuilderList() {
        if (seatsBuilder_ != null) {
          return seatsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(seats_);
        }
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public protocols.bull.over.seat_t.Builder addSeatsBuilder() {
        return getSeatsFieldBuilder().addBuilder(
            protocols.bull.over.seat_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public protocols.bull.over.seat_t.Builder addSeatsBuilder(
          int index) {
        return getSeatsFieldBuilder().addBuilder(
            index, protocols.bull.over.seat_t.getDefaultInstance());
      }
      /**
       * <pre>
       * 座位信息
       * </pre>
       *
       * <code>repeated .seat_t seats = 3;</code>
       */
      public java.util.List<protocols.bull.over.seat_t.Builder> 
           getSeatsBuilderList() {
        return getSeatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocols.bull.over.seat_t, protocols.bull.over.seat_t.Builder, protocols.bull.over.seat_tOrBuilder> 
          getSeatsFieldBuilder() {
        if (seatsBuilder_ == null) {
          seatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocols.bull.over.seat_t, protocols.bull.over.seat_t.Builder, protocols.bull.over.seat_tOrBuilder>(
                  seats_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          seats_ = null;
        }
        return seatsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:response)
    }

    // @@protoc_insertion_point(class_scope:response)
    private static final protocols.bull.over.response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.bull.over.response();
    }

    public static protocols.bull.over.response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<response>
        PARSER = new com.google.protobuf.AbstractParser<response>() {
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    public protocols.bull.over.response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface seat_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:seat_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 座位ID
     * </pre>
     *
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * 座位ID
     * </pre>
     *
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * 牌型
     * </pre>
     *
     * <code>required uint32 rank = 3;</code>
     */
    boolean hasRank();
    /**
     * <pre>
     * 牌型
     * </pre>
     *
     * <code>required uint32 rank = 3;</code>
     */
    int getRank();

    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    java.util.List<java.lang.Integer> getShowList();
    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    int getShowCount();
    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    int getShow(int index);

    /**
     * <pre>
     * 单局分数
     * </pre>
     *
     * <code>required sint32 scores = 5;</code>
     */
    boolean hasScores();
    /**
     * <pre>
     * 单局分数
     * </pre>
     *
     * <code>required sint32 scores = 5;</code>
     */
    int getScores();

    /**
     * <pre>
     * 总分
     * </pre>
     *
     * <code>required sint32 total = 6;</code>
     */
    boolean hasTotal();
    /**
     * <pre>
     * 总分
     * </pre>
     *
     * <code>required sint32 total = 6;</code>
     */
    int getTotal();

    /**
     * <pre>
     * 倍数
     * </pre>
     *
     * <code>required uint32 multiple = 7;</code>
     */
    boolean hasMultiple();
    /**
     * <pre>
     * 倍数
     * </pre>
     *
     * <code>required uint32 multiple = 7;</code>
     */
    int getMultiple();

    /**
     * <pre>
     * 单局抽水（预留后续需要显示时用）
     * </pre>
     *
     * <code>optional float draw = 8;</code>
     */
    boolean hasDraw();
    /**
     * <pre>
     * 单局抽水（预留后续需要显示时用）
     * </pre>
     *
     * <code>optional float draw = 8;</code>
     */
    float getDraw();
  }
  /**
   * <pre>
   * 座位
   * </pre>
   *
   * Protobuf type {@code seat_t}
   */
  public  static final class seat_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:seat_t)
      seat_tOrBuilder {
    // Use seat_t.newBuilder() to construct.
    private seat_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private seat_t() {
      id_ = 0;
      rank_ = 0;
      show_ = java.util.Collections.emptyList();
      scores_ = 0;
      total_ = 0;
      multiple_ = 0;
      draw_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private seat_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              rank_ = input.readUInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                show_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              show_.add(input.readUInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                show_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                show_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              scores_ = input.readSInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              total_ = input.readSInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              multiple_ = input.readUInt32();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000020;
              draw_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          show_ = java.util.Collections.unmodifiableList(show_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.bull.over.internal_static_seat_t_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.bull.over.internal_static_seat_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.bull.over.seat_t.class, protocols.bull.over.seat_t.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 座位ID
     * </pre>
     *
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 座位ID
     * </pre>
     *
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int RANK_FIELD_NUMBER = 3;
    private int rank_;
    /**
     * <pre>
     * 牌型
     * </pre>
     *
     * <code>required uint32 rank = 3;</code>
     */
    public boolean hasRank() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 牌型
     * </pre>
     *
     * <code>required uint32 rank = 3;</code>
     */
    public int getRank() {
      return rank_;
    }

    public static final int SHOW_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> show_;
    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getShowList() {
      return show_;
    }
    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    public int getShowCount() {
      return show_.size();
    }
    /**
     * <pre>
     * 摊牌
     * </pre>
     *
     * <code>repeated uint32 show = 4;</code>
     */
    public int getShow(int index) {
      return show_.get(index);
    }

    public static final int SCORES_FIELD_NUMBER = 5;
    private int scores_;
    /**
     * <pre>
     * 单局分数
     * </pre>
     *
     * <code>required sint32 scores = 5;</code>
     */
    public boolean hasScores() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 单局分数
     * </pre>
     *
     * <code>required sint32 scores = 5;</code>
     */
    public int getScores() {
      return scores_;
    }

    public static final int TOTAL_FIELD_NUMBER = 6;
    private int total_;
    /**
     * <pre>
     * 总分
     * </pre>
     *
     * <code>required sint32 total = 6;</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 总分
     * </pre>
     *
     * <code>required sint32 total = 6;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int MULTIPLE_FIELD_NUMBER = 7;
    private int multiple_;
    /**
     * <pre>
     * 倍数
     * </pre>
     *
     * <code>required uint32 multiple = 7;</code>
     */
    public boolean hasMultiple() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 倍数
     * </pre>
     *
     * <code>required uint32 multiple = 7;</code>
     */
    public int getMultiple() {
      return multiple_;
    }

    public static final int DRAW_FIELD_NUMBER = 8;
    private float draw_;
    /**
     * <pre>
     * 单局抽水（预留后续需要显示时用）
     * </pre>
     *
     * <code>optional float draw = 8;</code>
     */
    public boolean hasDraw() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 单局抽水（预留后续需要显示时用）
     * </pre>
     *
     * <code>optional float draw = 8;</code>
     */
    public float getDraw() {
      return draw_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScores()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMultiple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(3, rank_);
      }
      for (int i = 0; i < show_.size(); i++) {
        output.writeUInt32(4, show_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(5, scores_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(6, total_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(7, multiple_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(8, draw_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, rank_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < show_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(show_.get(i));
        }
        size += dataSize;
        size += 1 * getShowList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, scores_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, total_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, multiple_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, draw_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.bull.over.seat_t)) {
        return super.equals(obj);
      }
      protocols.bull.over.seat_t other = (protocols.bull.over.seat_t) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasRank() == other.hasRank());
      if (hasRank()) {
        result = result && (getRank()
            == other.getRank());
      }
      result = result && getShowList()
          .equals(other.getShowList());
      result = result && (hasScores() == other.hasScores());
      if (hasScores()) {
        result = result && (getScores()
            == other.getScores());
      }
      result = result && (hasTotal() == other.hasTotal());
      if (hasTotal()) {
        result = result && (getTotal()
            == other.getTotal());
      }
      result = result && (hasMultiple() == other.hasMultiple());
      if (hasMultiple()) {
        result = result && (getMultiple()
            == other.getMultiple());
      }
      result = result && (hasDraw() == other.hasDraw());
      if (hasDraw()) {
        result = result && (
            java.lang.Float.floatToIntBits(getDraw())
            == java.lang.Float.floatToIntBits(
                other.getDraw()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasRank()) {
        hash = (37 * hash) + RANK_FIELD_NUMBER;
        hash = (53 * hash) + getRank();
      }
      if (getShowCount() > 0) {
        hash = (37 * hash) + SHOW_FIELD_NUMBER;
        hash = (53 * hash) + getShowList().hashCode();
      }
      if (hasScores()) {
        hash = (37 * hash) + SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getScores();
      }
      if (hasTotal()) {
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
      }
      if (hasMultiple()) {
        hash = (37 * hash) + MULTIPLE_FIELD_NUMBER;
        hash = (53 * hash) + getMultiple();
      }
      if (hasDraw()) {
        hash = (37 * hash) + DRAW_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getDraw());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.bull.over.seat_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.bull.over.seat_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.bull.over.seat_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.bull.over.seat_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.bull.over.seat_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.bull.over.seat_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.bull.over.seat_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.bull.over.seat_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.bull.over.seat_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.bull.over.seat_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.bull.over.seat_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 座位
     * </pre>
     *
     * Protobuf type {@code seat_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:seat_t)
        protocols.bull.over.seat_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.bull.over.internal_static_seat_t_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.bull.over.internal_static_seat_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.bull.over.seat_t.class, protocols.bull.over.seat_t.Builder.class);
      }

      // Construct using protocols.bull.over.seat_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        show_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        scores_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        multiple_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        draw_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.bull.over.internal_static_seat_t_descriptor;
      }

      public protocols.bull.over.seat_t getDefaultInstanceForType() {
        return protocols.bull.over.seat_t.getDefaultInstance();
      }

      public protocols.bull.over.seat_t build() {
        protocols.bull.over.seat_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocols.bull.over.seat_t buildPartial() {
        protocols.bull.over.seat_t result = new protocols.bull.over.seat_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rank_ = rank_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          show_ = java.util.Collections.unmodifiableList(show_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.show_ = show_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.scores_ = scores_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.total_ = total_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.multiple_ = multiple_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.draw_ = draw_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.bull.over.seat_t) {
          return mergeFrom((protocols.bull.over.seat_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.bull.over.seat_t other) {
        if (other == protocols.bull.over.seat_t.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (!other.show_.isEmpty()) {
          if (show_.isEmpty()) {
            show_ = other.show_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureShowIsMutable();
            show_.addAll(other.show_);
          }
          onChanged();
        }
        if (other.hasScores()) {
          setScores(other.getScores());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasMultiple()) {
          setMultiple(other.getMultiple());
        }
        if (other.hasDraw()) {
          setDraw(other.getDraw());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasRank()) {
          return false;
        }
        if (!hasScores()) {
          return false;
        }
        if (!hasTotal()) {
          return false;
        }
        if (!hasMultiple()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.bull.over.seat_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.bull.over.seat_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * 座位ID
       * </pre>
       *
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 座位ID
       * </pre>
       *
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 座位ID
       * </pre>
       *
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 座位ID
       * </pre>
       *
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int rank_ ;
      /**
       * <pre>
       * 牌型
       * </pre>
       *
       * <code>required uint32 rank = 3;</code>
       */
      public boolean hasRank() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 牌型
       * </pre>
       *
       * <code>required uint32 rank = 3;</code>
       */
      public int getRank() {
        return rank_;
      }
      /**
       * <pre>
       * 牌型
       * </pre>
       *
       * <code>required uint32 rank = 3;</code>
       */
      public Builder setRank(int value) {
        bitField0_ |= 0x00000002;
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 牌型
       * </pre>
       *
       * <code>required uint32 rank = 3;</code>
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rank_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> show_ = java.util.Collections.emptyList();
      private void ensureShowIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          show_ = new java.util.ArrayList<java.lang.Integer>(show_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getShowList() {
        return java.util.Collections.unmodifiableList(show_);
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public int getShowCount() {
        return show_.size();
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public int getShow(int index) {
        return show_.get(index);
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public Builder setShow(
          int index, int value) {
        ensureShowIsMutable();
        show_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public Builder addShow(int value) {
        ensureShowIsMutable();
        show_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public Builder addAllShow(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureShowIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, show_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 摊牌
       * </pre>
       *
       * <code>repeated uint32 show = 4;</code>
       */
      public Builder clearShow() {
        show_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int scores_ ;
      /**
       * <pre>
       * 单局分数
       * </pre>
       *
       * <code>required sint32 scores = 5;</code>
       */
      public boolean hasScores() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 单局分数
       * </pre>
       *
       * <code>required sint32 scores = 5;</code>
       */
      public int getScores() {
        return scores_;
      }
      /**
       * <pre>
       * 单局分数
       * </pre>
       *
       * <code>required sint32 scores = 5;</code>
       */
      public Builder setScores(int value) {
        bitField0_ |= 0x00000008;
        scores_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单局分数
       * </pre>
       *
       * <code>required sint32 scores = 5;</code>
       */
      public Builder clearScores() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scores_ = 0;
        onChanged();
        return this;
      }

      private int total_ ;
      /**
       * <pre>
       * 总分
       * </pre>
       *
       * <code>required sint32 total = 6;</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 总分
       * </pre>
       *
       * <code>required sint32 total = 6;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <pre>
       * 总分
       * </pre>
       *
       * <code>required sint32 total = 6;</code>
       */
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000010;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 总分
       * </pre>
       *
       * <code>required sint32 total = 6;</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000010);
        total_ = 0;
        onChanged();
        return this;
      }

      private int multiple_ ;
      /**
       * <pre>
       * 倍数
       * </pre>
       *
       * <code>required uint32 multiple = 7;</code>
       */
      public boolean hasMultiple() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 倍数
       * </pre>
       *
       * <code>required uint32 multiple = 7;</code>
       */
      public int getMultiple() {
        return multiple_;
      }
      /**
       * <pre>
       * 倍数
       * </pre>
       *
       * <code>required uint32 multiple = 7;</code>
       */
      public Builder setMultiple(int value) {
        bitField0_ |= 0x00000020;
        multiple_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 倍数
       * </pre>
       *
       * <code>required uint32 multiple = 7;</code>
       */
      public Builder clearMultiple() {
        bitField0_ = (bitField0_ & ~0x00000020);
        multiple_ = 0;
        onChanged();
        return this;
      }

      private float draw_ ;
      /**
       * <pre>
       * 单局抽水（预留后续需要显示时用）
       * </pre>
       *
       * <code>optional float draw = 8;</code>
       */
      public boolean hasDraw() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 单局抽水（预留后续需要显示时用）
       * </pre>
       *
       * <code>optional float draw = 8;</code>
       */
      public float getDraw() {
        return draw_;
      }
      /**
       * <pre>
       * 单局抽水（预留后续需要显示时用）
       * </pre>
       *
       * <code>optional float draw = 8;</code>
       */
      public Builder setDraw(float value) {
        bitField0_ |= 0x00000040;
        draw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 单局抽水（预留后续需要显示时用）
       * </pre>
       *
       * <code>optional float draw = 8;</code>
       */
      public Builder clearDraw() {
        bitField0_ = (bitField0_ & ~0x00000040);
        draw_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:seat_t)
    }

    // @@protoc_insertion_point(class_scope:seat_t)
    private static final protocols.bull.over.seat_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.bull.over.seat_t();
    }

    public static protocols.bull.over.seat_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<seat_t>
        PARSER = new com.google.protobuf.AbstractParser<seat_t>() {
      public seat_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new seat_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<seat_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<seat_t> getParserForType() {
      return PARSER;
    }

    public protocols.bull.over.seat_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_seat_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_seat_t_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017bull/over.proto\"B\n\010response\022\016\n\006inning\030" +
      "\001 \002(\r\022\016\n\006dealer\030\002 \002(\r\022\026\n\005seats\030\003 \003(\0132\007.s" +
      "eat_t\"o\n\006seat_t\022\n\n\002id\030\001 \002(\r\022\014\n\004rank\030\003 \002(" +
      "\r\022\014\n\004show\030\004 \003(\r\022\016\n\006scores\030\005 \002(\021\022\r\n\005total" +
      "\030\006 \002(\021\022\020\n\010multiple\030\007 \002(\r\022\014\n\004draw\030\010 \001(\002B\026" +
      "\n\016protocols.bullB\004over"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Inning", "Dealer", "Seats", });
    internal_static_seat_t_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_seat_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_seat_t_descriptor,
        new java.lang.String[] { "Id", "Rank", "Show", "Scores", "Total", "Multiple", "Draw", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
